apiVersion: batch/v1
kind: CronJob
metadata:
  name: garbage-collection-manager
  labels:
    control-plane: garbage-collection-manager
    app.kubernetes.io/name: cronjob
    app.kubernetes.io/instance: garbage-collection-manager
    app.kubernetes.io/component: garbage-collector
    app.kubernetes.io/created-by: k8s-backup-operator
    app.kubernetes.io/part-of: k8s-backup-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  schedule: "{{ .Values.retention.garbageCollectionCron }}"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
          - args:
            - gc
            env:
              - name: STAGE
                value: "production"
              - name: LOG_LEVEL
                value: "debug"
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            image: controller:latest
            imagePullPolicy: IfNotPresent
            name: garbage-collector
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
            resources:
              limits:
                cpu: 500m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 64Mi
