// Code generated by mockery v2.53.5. DO NOT EDIT.

package schedule

import (
	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockConditionManager is an autogenerated mock type for the ConditionManager type
type MockConditionManager struct {
	mock.Mock
}

type MockConditionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConditionManager) EXPECT() *MockConditionManager_Expecter {
	return &MockConditionManager_Expecter{mock: &_m.Mock}
}

// ComputeReady provides a mock function with given fields: schedule
func (_m *MockConditionManager) ComputeReady(schedule *v1.BackupSchedule) {
	_m.Called(schedule)
}

// MockConditionManager_ComputeReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputeReady'
type MockConditionManager_ComputeReady_Call struct {
	*mock.Call
}

// ComputeReady is a helper method to define mock.On call
//   - schedule *v1.BackupSchedule
func (_e *MockConditionManager_Expecter) ComputeReady(schedule interface{}) *MockConditionManager_ComputeReady_Call {
	return &MockConditionManager_ComputeReady_Call{Call: _e.mock.On("ComputeReady", schedule)}
}

func (_c *MockConditionManager_ComputeReady_Call) Run(run func(schedule *v1.BackupSchedule)) *MockConditionManager_ComputeReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *MockConditionManager_ComputeReady_Call) Return() *MockConditionManager_ComputeReady_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConditionManager_ComputeReady_Call) RunAndReturn(run func(*v1.BackupSchedule)) *MockConditionManager_ComputeReady_Call {
	_c.Run(run)
	return _c
}

// MarkAcceptanceNotEvaluated provides a mock function with given fields: schedule, err
func (_m *MockConditionManager) MarkAcceptanceNotEvaluated(schedule *v1.BackupSchedule, err error) {
	_m.Called(schedule, err)
}

// MockConditionManager_MarkAcceptanceNotEvaluated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAcceptanceNotEvaluated'
type MockConditionManager_MarkAcceptanceNotEvaluated_Call struct {
	*mock.Call
}

// MarkAcceptanceNotEvaluated is a helper method to define mock.On call
//   - schedule *v1.BackupSchedule
//   - err error
func (_e *MockConditionManager_Expecter) MarkAcceptanceNotEvaluated(schedule interface{}, err interface{}) *MockConditionManager_MarkAcceptanceNotEvaluated_Call {
	return &MockConditionManager_MarkAcceptanceNotEvaluated_Call{Call: _e.mock.On("MarkAcceptanceNotEvaluated", schedule, err)}
}

func (_c *MockConditionManager_MarkAcceptanceNotEvaluated_Call) Run(run func(schedule *v1.BackupSchedule, err error)) *MockConditionManager_MarkAcceptanceNotEvaluated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.BackupSchedule), args[1].(error))
	})
	return _c
}

func (_c *MockConditionManager_MarkAcceptanceNotEvaluated_Call) Return() *MockConditionManager_MarkAcceptanceNotEvaluated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConditionManager_MarkAcceptanceNotEvaluated_Call) RunAndReturn(run func(*v1.BackupSchedule, error)) *MockConditionManager_MarkAcceptanceNotEvaluated_Call {
	_c.Run(run)
	return _c
}

// MarkAccepted provides a mock function with given fields: schedule
func (_m *MockConditionManager) MarkAccepted(schedule *v1.BackupSchedule) {
	_m.Called(schedule)
}

// MockConditionManager_MarkAccepted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAccepted'
type MockConditionManager_MarkAccepted_Call struct {
	*mock.Call
}

// MarkAccepted is a helper method to define mock.On call
//   - schedule *v1.BackupSchedule
func (_e *MockConditionManager_Expecter) MarkAccepted(schedule interface{}) *MockConditionManager_MarkAccepted_Call {
	return &MockConditionManager_MarkAccepted_Call{Call: _e.mock.On("MarkAccepted", schedule)}
}

func (_c *MockConditionManager_MarkAccepted_Call) Run(run func(schedule *v1.BackupSchedule)) *MockConditionManager_MarkAccepted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *MockConditionManager_MarkAccepted_Call) Return() *MockConditionManager_MarkAccepted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConditionManager_MarkAccepted_Call) RunAndReturn(run func(*v1.BackupSchedule)) *MockConditionManager_MarkAccepted_Call {
	_c.Run(run)
	return _c
}

// MarkCronJobNotSynced provides a mock function with given fields: schedule, err
func (_m *MockConditionManager) MarkCronJobNotSynced(schedule *v1.BackupSchedule, err error) {
	_m.Called(schedule, err)
}

// MockConditionManager_MarkCronJobNotSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCronJobNotSynced'
type MockConditionManager_MarkCronJobNotSynced_Call struct {
	*mock.Call
}

// MarkCronJobNotSynced is a helper method to define mock.On call
//   - schedule *v1.BackupSchedule
//   - err error
func (_e *MockConditionManager_Expecter) MarkCronJobNotSynced(schedule interface{}, err interface{}) *MockConditionManager_MarkCronJobNotSynced_Call {
	return &MockConditionManager_MarkCronJobNotSynced_Call{Call: _e.mock.On("MarkCronJobNotSynced", schedule, err)}
}

func (_c *MockConditionManager_MarkCronJobNotSynced_Call) Run(run func(schedule *v1.BackupSchedule, err error)) *MockConditionManager_MarkCronJobNotSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.BackupSchedule), args[1].(error))
	})
	return _c
}

func (_c *MockConditionManager_MarkCronJobNotSynced_Call) Return() *MockConditionManager_MarkCronJobNotSynced_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConditionManager_MarkCronJobNotSynced_Call) RunAndReturn(run func(*v1.BackupSchedule, error)) *MockConditionManager_MarkCronJobNotSynced_Call {
	_c.Run(run)
	return _c
}

// MarkCronJobSynced provides a mock function with given fields: schedule
func (_m *MockConditionManager) MarkCronJobSynced(schedule *v1.BackupSchedule) {
	_m.Called(schedule)
}

// MockConditionManager_MarkCronJobSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCronJobSynced'
type MockConditionManager_MarkCronJobSynced_Call struct {
	*mock.Call
}

// MarkCronJobSynced is a helper method to define mock.On call
//   - schedule *v1.BackupSchedule
func (_e *MockConditionManager_Expecter) MarkCronJobSynced(schedule interface{}) *MockConditionManager_MarkCronJobSynced_Call {
	return &MockConditionManager_MarkCronJobSynced_Call{Call: _e.mock.On("MarkCronJobSynced", schedule)}
}

func (_c *MockConditionManager_MarkCronJobSynced_Call) Run(run func(schedule *v1.BackupSchedule)) *MockConditionManager_MarkCronJobSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *MockConditionManager_MarkCronJobSynced_Call) Return() *MockConditionManager_MarkCronJobSynced_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConditionManager_MarkCronJobSynced_Call) RunAndReturn(run func(*v1.BackupSchedule)) *MockConditionManager_MarkCronJobSynced_Call {
	_c.Run(run)
	return _c
}

// MarkDeleting provides a mock function with given fields: schedule
func (_m *MockConditionManager) MarkDeleting(schedule *v1.BackupSchedule) {
	_m.Called(schedule)
}

// MockConditionManager_MarkDeleting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDeleting'
type MockConditionManager_MarkDeleting_Call struct {
	*mock.Call
}

// MarkDeleting is a helper method to define mock.On call
//   - schedule *v1.BackupSchedule
func (_e *MockConditionManager_Expecter) MarkDeleting(schedule interface{}) *MockConditionManager_MarkDeleting_Call {
	return &MockConditionManager_MarkDeleting_Call{Call: _e.mock.On("MarkDeleting", schedule)}
}

func (_c *MockConditionManager_MarkDeleting_Call) Run(run func(schedule *v1.BackupSchedule)) *MockConditionManager_MarkDeleting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *MockConditionManager_MarkDeleting_Call) Return() *MockConditionManager_MarkDeleting_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConditionManager_MarkDeleting_Call) RunAndReturn(run func(*v1.BackupSchedule)) *MockConditionManager_MarkDeleting_Call {
	_c.Run(run)
	return _c
}

// MarkInvalid provides a mock function with given fields: schedule, err
func (_m *MockConditionManager) MarkInvalid(schedule *v1.BackupSchedule, err error) {
	_m.Called(schedule, err)
}

// MockConditionManager_MarkInvalid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkInvalid'
type MockConditionManager_MarkInvalid_Call struct {
	*mock.Call
}

// MarkInvalid is a helper method to define mock.On call
//   - schedule *v1.BackupSchedule
//   - err error
func (_e *MockConditionManager_Expecter) MarkInvalid(schedule interface{}, err interface{}) *MockConditionManager_MarkInvalid_Call {
	return &MockConditionManager_MarkInvalid_Call{Call: _e.mock.On("MarkInvalid", schedule, err)}
}

func (_c *MockConditionManager_MarkInvalid_Call) Run(run func(schedule *v1.BackupSchedule, err error)) *MockConditionManager_MarkInvalid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.BackupSchedule), args[1].(error))
	})
	return _c
}

func (_c *MockConditionManager_MarkInvalid_Call) Return() *MockConditionManager_MarkInvalid_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConditionManager_MarkInvalid_Call) RunAndReturn(run func(*v1.BackupSchedule, error)) *MockConditionManager_MarkInvalid_Call {
	_c.Run(run)
	return _c
}

// NewMockConditionManager creates a new instance of MockConditionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConditionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConditionManager {
	mock := &MockConditionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
