// Code generated by mockery v2.53.5. DO NOT EDIT.

package schedule

import (
	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockValidator is an autogenerated mock type for the validator type
type mockValidator struct {
	mock.Mock
}

type mockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockValidator) EXPECT() *mockValidator_Expecter {
	return &mockValidator_Expecter{mock: &_m.Mock}
}

// validate provides a mock function with given fields: schedule
func (_m *mockValidator) validate(schedule *v1.BackupSchedule) error {
	ret := _m.Called(schedule)

	if len(ret) == 0 {
		panic("no return value specified for validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.BackupSchedule) error); ok {
		r0 = rf(schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockValidator_validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'validate'
type mockValidator_validate_Call struct {
	*mock.Call
}

// validate is a helper method to define mock.On call
//   - schedule *v1.BackupSchedule
func (_e *mockValidator_Expecter) validate(schedule interface{}) *mockValidator_validate_Call {
	return &mockValidator_validate_Call{Call: _e.mock.On("validate", schedule)}
}

func (_c *mockValidator_validate_Call) Run(run func(schedule *v1.BackupSchedule)) *mockValidator_validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *mockValidator_validate_Call) Return(_a0 error) *mockValidator_validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockValidator_validate_Call) RunAndReturn(run func(*v1.BackupSchedule) error) *mockValidator_validate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockValidator creates a new instance of mockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockValidator {
	mock := &mockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
