// Code generated by mockery v2.53.5. DO NOT EDIT.

package schedule

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockMetadataManager is an autogenerated mock type for the metadataManager type
type mockMetadataManager struct {
	mock.Mock
}

type mockMetadataManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMetadataManager) EXPECT() *mockMetadataManager_Expecter {
	return &mockMetadataManager_Expecter{mock: &_m.Mock}
}

// ensure provides a mock function with given fields: ctx, schedule
func (_m *mockMetadataManager) ensure(ctx context.Context, schedule *v1.BackupSchedule) error {
	ret := _m.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for ensure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule) error); ok {
		r0 = rf(ctx, schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMetadataManager_ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensure'
type mockMetadataManager_ensure_Call struct {
	*mock.Call
}

// ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - schedule *v1.BackupSchedule
func (_e *mockMetadataManager_Expecter) ensure(ctx interface{}, schedule interface{}) *mockMetadataManager_ensure_Call {
	return &mockMetadataManager_ensure_Call{Call: _e.mock.On("ensure", ctx, schedule)}
}

func (_c *mockMetadataManager_ensure_Call) Run(run func(ctx context.Context, schedule *v1.BackupSchedule)) *mockMetadataManager_ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *mockMetadataManager_ensure_Call) Return(_a0 error) *mockMetadataManager_ensure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMetadataManager_ensure_Call) RunAndReturn(run func(context.Context, *v1.BackupSchedule) error) *mockMetadataManager_ensure_Call {
	_c.Call.Return(run)
	return _c
}

// remove provides a mock function with given fields: ctx, schedule
func (_m *mockMetadataManager) remove(ctx context.Context, schedule *v1.BackupSchedule) error {
	ret := _m.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule) error); ok {
		r0 = rf(ctx, schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMetadataManager_remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'remove'
type mockMetadataManager_remove_Call struct {
	*mock.Call
}

// remove is a helper method to define mock.On call
//   - ctx context.Context
//   - schedule *v1.BackupSchedule
func (_e *mockMetadataManager_Expecter) remove(ctx interface{}, schedule interface{}) *mockMetadataManager_remove_Call {
	return &mockMetadataManager_remove_Call{Call: _e.mock.On("remove", ctx, schedule)}
}

func (_c *mockMetadataManager_remove_Call) Run(run func(ctx context.Context, schedule *v1.BackupSchedule)) *mockMetadataManager_remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *mockMetadataManager_remove_Call) Return(_a0 error) *mockMetadataManager_remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMetadataManager_remove_Call) RunAndReturn(run func(context.Context, *v1.BackupSchedule) error) *mockMetadataManager_remove_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMetadataManager creates a new instance of mockMetadataManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMetadataManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMetadataManager {
	mock := &mockMetadataManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
