// Code generated by mockery v2.53.5. DO NOT EDIT.

package blueprint

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FindDogusOfBlueprint provides a mock function with no fields
func (_m *MockRepository) FindDogusOfBlueprint() (BlueprintWithDogus, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindDogusOfBlueprint")
	}

	var r0 BlueprintWithDogus
	var r1 error
	if rf, ok := ret.Get(0).(func() (BlueprintWithDogus, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() BlueprintWithDogus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(BlueprintWithDogus)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindDogusOfBlueprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDogusOfBlueprint'
type MockRepository_FindDogusOfBlueprint_Call struct {
	*mock.Call
}

// FindDogusOfBlueprint is a helper method to define mock.On call
func (_e *MockRepository_Expecter) FindDogusOfBlueprint() *MockRepository_FindDogusOfBlueprint_Call {
	return &MockRepository_FindDogusOfBlueprint_Call{Call: _e.mock.On("FindDogusOfBlueprint")}
}

func (_c *MockRepository_FindDogusOfBlueprint_Call) Run(run func()) *MockRepository_FindDogusOfBlueprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_FindDogusOfBlueprint_Call) Return(_a0 BlueprintWithDogus, _a1 error) *MockRepository_FindDogusOfBlueprint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindDogusOfBlueprint_Call) RunAndReturn(run func() (BlueprintWithDogus, error)) *MockRepository_FindDogusOfBlueprint_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
