// Code generated by mockery v2.53.5. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockConfigGetter is an autogenerated mock type for the configGetter type
type mockConfigGetter struct {
	mock.Mock
}

type mockConfigGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigGetter) EXPECT() *mockConfigGetter_Expecter {
	return &mockConfigGetter_Expecter{mock: &_m.Mock}
}

// GetRetryLimit provides a mock function with given fields: _a0
func (_m *mockConfigGetter) GetRetryLimit(_a0 context.Context) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRetryLimit")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigGetter_GetRetryLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetryLimit'
type mockConfigGetter_GetRetryLimit_Call struct {
	*mock.Call
}

// GetRetryLimit is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockConfigGetter_Expecter) GetRetryLimit(_a0 interface{}) *mockConfigGetter_GetRetryLimit_Call {
	return &mockConfigGetter_GetRetryLimit_Call{Call: _e.mock.On("GetRetryLimit", _a0)}
}

func (_c *mockConfigGetter_GetRetryLimit_Call) Run(run func(_a0 context.Context)) *mockConfigGetter_GetRetryLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockConfigGetter_GetRetryLimit_Call) Return(_a0 int, _a1 error) *mockConfigGetter_GetRetryLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigGetter_GetRetryLimit_Call) RunAndReturn(run func(context.Context) (int, error)) *mockConfigGetter_GetRetryLimit_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigGetter creates a new instance of mockConfigGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigGetter {
	mock := &mockConfigGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
