// Code generated by mockery v2.20.0. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockCleanupManager is an autogenerated mock type for the cleanupManager type
type mockCleanupManager struct {
	mock.Mock
}

type mockCleanupManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCleanupManager) EXPECT() *mockCleanupManager_Expecter {
	return &mockCleanupManager_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: ctx
func (_m *mockCleanupManager) Cleanup(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCleanupManager_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type mockCleanupManager_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockCleanupManager_Expecter) Cleanup(ctx interface{}) *mockCleanupManager_Cleanup_Call {
	return &mockCleanupManager_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *mockCleanupManager_Cleanup_Call) Run(run func(ctx context.Context)) *mockCleanupManager_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockCleanupManager_Cleanup_Call) Return(_a0 error) *mockCleanupManager_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCleanupManager_Cleanup_Call) RunAndReturn(run func(context.Context) error) *mockCleanupManager_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockCleanupManager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockCleanupManager creates a new instance of mockCleanupManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockCleanupManager(t mockConstructorTestingTnewMockCleanupManager) *mockCleanupManager {
	mock := &mockCleanupManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
