// Code generated by mockery v2.53.5. DO NOT EDIT.

package scale

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// ScaleDown provides a mock function with given fields: ctx
func (_m *MockManager) ScaleDown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ScaleDown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_ScaleDown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScaleDown'
type MockManager_ScaleDown_Call struct {
	*mock.Call
}

// ScaleDown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) ScaleDown(ctx interface{}) *MockManager_ScaleDown_Call {
	return &MockManager_ScaleDown_Call{Call: _e.mock.On("ScaleDown", ctx)}
}

func (_c *MockManager_ScaleDown_Call) Run(run func(ctx context.Context)) *MockManager_ScaleDown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockManager_ScaleDown_Call) Return(_a0 error) *MockManager_ScaleDown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_ScaleDown_Call) RunAndReturn(run func(context.Context) error) *MockManager_ScaleDown_Call {
	_c.Call.Return(run)
	return _c
}

// ScaleUp provides a mock function with given fields: ctx
func (_m *MockManager) ScaleUp(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ScaleUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_ScaleUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScaleUp'
type MockManager_ScaleUp_Call struct {
	*mock.Call
}

// ScaleUp is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) ScaleUp(ctx interface{}) *MockManager_ScaleUp_Call {
	return &MockManager_ScaleUp_Call{Call: _e.mock.On("ScaleUp", ctx)}
}

func (_c *MockManager_ScaleUp_Call) Run(run func(ctx context.Context)) *MockManager_ScaleUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockManager_ScaleUp_Call) Return(_a0 error) *MockManager_ScaleUp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_ScaleUp_Call) RunAndReturn(run func(context.Context) error) *MockManager_ScaleUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
