// Code generated by mockery v2.20.0. DO NOT EDIT.

package additionalimages

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdater is an autogenerated mock type for the Updater type
type MockUpdater struct {
	mock.Mock
}

type MockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdater) EXPECT() *MockUpdater_Expecter {
	return &MockUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: ctx
func (_m *MockUpdater) Update(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUpdater_Expecter) Update(ctx interface{}) *MockUpdater_Update_Call {
	return &MockUpdater_Update_Call{Call: _e.mock.On("Update", ctx)}
}

func (_c *MockUpdater_Update_Call) Run(run func(ctx context.Context)) *MockUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUpdater_Update_Call) Return(_a0 error) *MockUpdater_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdater_Update_Call) RunAndReturn(run func(context.Context) error) *MockUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUpdater creates a new instance of MockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUpdater(t mockConstructorTestingTNewMockUpdater) *MockUpdater {
	mock := &MockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
