// Code generated by mockery v2.20.0. DO NOT EDIT.

package additionalimages

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGetter is an autogenerated mock type for the Getter type
type MockGetter struct {
	mock.Mock
}

type MockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetter) EXPECT() *MockGetter_Expecter {
	return &MockGetter_Expecter{mock: &_m.Mock}
}

// ImageForKey provides a mock function with given fields: ctx, key
func (_m *MockGetter) ImageForKey(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetter_ImageForKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageForKey'
type MockGetter_ImageForKey_Call struct {
	*mock.Call
}

// ImageForKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockGetter_Expecter) ImageForKey(ctx interface{}, key interface{}) *MockGetter_ImageForKey_Call {
	return &MockGetter_ImageForKey_Call{Call: _e.mock.On("ImageForKey", ctx, key)}
}

func (_c *MockGetter_ImageForKey_Call) Run(run func(ctx context.Context, key string)) *MockGetter_ImageForKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetter_ImageForKey_Call) Return(_a0 string, _a1 error) *MockGetter_ImageForKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetter_ImageForKey_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockGetter_ImageForKey_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGetter creates a new instance of MockGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGetter(t mockConstructorTestingTNewMockGetter) *MockGetter {
	mock := &MockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
