// Code generated by mockery v2.53.5. DO NOT EDIT.

package restore

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	types "k8s.io/apimachinery/pkg/types"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// mockRestoreStatusClient is an autogenerated mock type for the restoreStatusClient type
type mockRestoreStatusClient struct {
	mock.Mock
}

type mockRestoreStatusClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRestoreStatusClient) EXPECT() *mockRestoreStatusClient_Expecter {
	return &mockRestoreStatusClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key, obj, opts
func (_m *mockRestoreStatusClient) Get(ctx context.Context, key types.NamespacedName, obj client.Object, opts ...client.GetOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, obj)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.NamespacedName, client.Object, ...client.GetOption) error); ok {
		r0 = rf(ctx, key, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRestoreStatusClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockRestoreStatusClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.NamespacedName
//   - obj client.Object
//   - opts ...client.GetOption
func (_e *mockRestoreStatusClient_Expecter) Get(ctx interface{}, key interface{}, obj interface{}, opts ...interface{}) *mockRestoreStatusClient_Get_Call {
	return &mockRestoreStatusClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, key, obj}, opts...)...)}
}

func (_c *mockRestoreStatusClient_Get_Call) Run(run func(ctx context.Context, key types.NamespacedName, obj client.Object, opts ...client.GetOption)) *mockRestoreStatusClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.GetOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.GetOption)
			}
		}
		run(args[0].(context.Context), args[1].(types.NamespacedName), args[2].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *mockRestoreStatusClient_Get_Call) Return(_a0 error) *mockRestoreStatusClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRestoreStatusClient_Get_Call) RunAndReturn(run func(context.Context, types.NamespacedName, client.Object, ...client.GetOption) error) *mockRestoreStatusClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *mockRestoreStatusClient) Status() client.SubResourceWriter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 client.SubResourceWriter
	if rf, ok := ret.Get(0).(func() client.SubResourceWriter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SubResourceWriter)
		}
	}

	return r0
}

// mockRestoreStatusClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type mockRestoreStatusClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *mockRestoreStatusClient_Expecter) Status() *mockRestoreStatusClient_Status_Call {
	return &mockRestoreStatusClient_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *mockRestoreStatusClient_Status_Call) Run(run func()) *mockRestoreStatusClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockRestoreStatusClient_Status_Call) Return(_a0 client.SubResourceWriter) *mockRestoreStatusClient_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRestoreStatusClient_Status_Call) RunAndReturn(run func() client.SubResourceWriter) *mockRestoreStatusClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRestoreStatusClient creates a new instance of mockRestoreStatusClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRestoreStatusClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRestoreStatusClient {
	mock := &mockRestoreStatusClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
