// Code generated by mockery v2.53.5. DO NOT EDIT.

package restore

import (
	context "context"

	repository "github.com/cloudogu/k8s-registry-lib/repository"
	mock "github.com/stretchr/testify/mock"
)

// mockMaintenanceModeSwitch is an autogenerated mock type for the maintenanceModeSwitch type
type mockMaintenanceModeSwitch struct {
	mock.Mock
}

type mockMaintenanceModeSwitch_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMaintenanceModeSwitch) EXPECT() *mockMaintenanceModeSwitch_Expecter {
	return &mockMaintenanceModeSwitch_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: ctx, description, force
func (_m *mockMaintenanceModeSwitch) Activate(ctx context.Context, description repository.MaintenanceModeDescription, force bool) error {
	ret := _m.Called(ctx, description, force)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.MaintenanceModeDescription, bool) error); ok {
		r0 = rf(ctx, description, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMaintenanceModeSwitch_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type mockMaintenanceModeSwitch_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - description repository.MaintenanceModeDescription
//   - force bool
func (_e *mockMaintenanceModeSwitch_Expecter) Activate(ctx interface{}, description interface{}, force interface{}) *mockMaintenanceModeSwitch_Activate_Call {
	return &mockMaintenanceModeSwitch_Activate_Call{Call: _e.mock.On("Activate", ctx, description, force)}
}

func (_c *mockMaintenanceModeSwitch_Activate_Call) Run(run func(ctx context.Context, description repository.MaintenanceModeDescription, force bool)) *mockMaintenanceModeSwitch_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.MaintenanceModeDescription), args[2].(bool))
	})
	return _c
}

func (_c *mockMaintenanceModeSwitch_Activate_Call) Return(_a0 error) *mockMaintenanceModeSwitch_Activate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMaintenanceModeSwitch_Activate_Call) RunAndReturn(run func(context.Context, repository.MaintenanceModeDescription, bool) error) *mockMaintenanceModeSwitch_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, force
func (_m *mockMaintenanceModeSwitch) Deactivate(ctx context.Context, force bool) error {
	ret := _m.Called(ctx, force)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMaintenanceModeSwitch_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type mockMaintenanceModeSwitch_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - force bool
func (_e *mockMaintenanceModeSwitch_Expecter) Deactivate(ctx interface{}, force interface{}) *mockMaintenanceModeSwitch_Deactivate_Call {
	return &mockMaintenanceModeSwitch_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, force)}
}

func (_c *mockMaintenanceModeSwitch_Deactivate_Call) Run(run func(ctx context.Context, force bool)) *mockMaintenanceModeSwitch_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *mockMaintenanceModeSwitch_Deactivate_Call) Return(_a0 error) *mockMaintenanceModeSwitch_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMaintenanceModeSwitch_Deactivate_Call) RunAndReturn(run func(context.Context, bool) error) *mockMaintenanceModeSwitch_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx
func (_m *mockMaintenanceModeSwitch) GetStatus(ctx context.Context) (repository.MaintenanceModeDescription, bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 repository.MaintenanceModeDescription
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.MaintenanceModeDescription, bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.MaintenanceModeDescription); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(repository.MaintenanceModeDescription)
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockMaintenanceModeSwitch_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type mockMaintenanceModeSwitch_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockMaintenanceModeSwitch_Expecter) GetStatus(ctx interface{}) *mockMaintenanceModeSwitch_GetStatus_Call {
	return &mockMaintenanceModeSwitch_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *mockMaintenanceModeSwitch_GetStatus_Call) Run(run func(ctx context.Context)) *mockMaintenanceModeSwitch_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockMaintenanceModeSwitch_GetStatus_Call) Return(_a0 repository.MaintenanceModeDescription, _a1 bool, _a2 error) *mockMaintenanceModeSwitch_GetStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockMaintenanceModeSwitch_GetStatus_Call) RunAndReturn(run func(context.Context) (repository.MaintenanceModeDescription, bool, error)) *mockMaintenanceModeSwitch_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMaintenanceModeSwitch creates a new instance of mockMaintenanceModeSwitch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMaintenanceModeSwitch(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMaintenanceModeSwitch {
	mock := &mockMaintenanceModeSwitch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
