// Code generated by mockery v2.53.5. DO NOT EDIT.

package restore

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockReconcileStage is an autogenerated mock type for the reconcileStage type
type mockReconcileStage struct {
	mock.Mock
}

type mockReconcileStage_Expecter struct {
	mock *mock.Mock
}

func (_m *mockReconcileStage) EXPECT() *mockReconcileStage_Expecter {
	return &mockReconcileStage_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, restore
func (_m *mockReconcileStage) Execute(ctx context.Context, restore *v1.Restore) stageOutcome {
	ret := _m.Called(ctx, restore)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 stageOutcome
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) stageOutcome); ok {
		r0 = rf(ctx, restore)
	} else {
		r0 = ret.Get(0).(stageOutcome)
	}

	return r0
}

// mockReconcileStage_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockReconcileStage_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
func (_e *mockReconcileStage_Expecter) Execute(ctx interface{}, restore interface{}) *mockReconcileStage_Execute_Call {
	return &mockReconcileStage_Execute_Call{Call: _e.mock.On("Execute", ctx, restore)}
}

func (_c *mockReconcileStage_Execute_Call) Run(run func(ctx context.Context, restore *v1.Restore)) *mockReconcileStage_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore))
	})
	return _c
}

func (_c *mockReconcileStage_Execute_Call) Return(_a0 stageOutcome) *mockReconcileStage_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockReconcileStage_Execute_Call) RunAndReturn(run func(context.Context, *v1.Restore) stageOutcome) *mockReconcileStage_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockReconcileStage creates a new instance of mockReconcileStage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockReconcileStage(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockReconcileStage {
	mock := &mockReconcileStage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
