// Code generated by mockery v2.20.0. DO NOT EDIT.

package velero

import mock "github.com/stretchr/testify/mock"

// mockRestoreManager is an autogenerated mock type for the restoreManager type
type mockRestoreManager struct {
	mock.Mock
}

type mockRestoreManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRestoreManager) EXPECT() *mockRestoreManager_Expecter {
	return &mockRestoreManager_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTnewMockRestoreManager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockRestoreManager creates a new instance of mockRestoreManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockRestoreManager(t mockConstructorTestingTnewMockRestoreManager) *mockRestoreManager {
	mock := &mockRestoreManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
