// Code generated by mockery v2.20.0. DO NOT EDIT.

package velero

import (
	mock "github.com/stretchr/testify/mock"
	watch "k8s.io/apimachinery/pkg/watch"
)

// mockEcosystemWatch is an autogenerated mock type for the ecosystemWatch type
type mockEcosystemWatch struct {
	mock.Mock
}

type mockEcosystemWatch_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEcosystemWatch) EXPECT() *mockEcosystemWatch_Expecter {
	return &mockEcosystemWatch_Expecter{mock: &_m.Mock}
}

// ResultChan provides a mock function with given fields:
func (_m *mockEcosystemWatch) ResultChan() <-chan watch.Event {
	ret := _m.Called()

	var r0 <-chan watch.Event
	if rf, ok := ret.Get(0).(func() <-chan watch.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan watch.Event)
		}
	}

	return r0
}

// mockEcosystemWatch_ResultChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResultChan'
type mockEcosystemWatch_ResultChan_Call struct {
	*mock.Call
}

// ResultChan is a helper method to define mock.On call
func (_e *mockEcosystemWatch_Expecter) ResultChan() *mockEcosystemWatch_ResultChan_Call {
	return &mockEcosystemWatch_ResultChan_Call{Call: _e.mock.On("ResultChan")}
}

func (_c *mockEcosystemWatch_ResultChan_Call) Run(run func()) *mockEcosystemWatch_ResultChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockEcosystemWatch_ResultChan_Call) Return(_a0 <-chan watch.Event) *mockEcosystemWatch_ResultChan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEcosystemWatch_ResultChan_Call) RunAndReturn(run func() <-chan watch.Event) *mockEcosystemWatch_ResultChan_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields:
func (_m *mockEcosystemWatch) Stop() {
	_m.Called()
}

// mockEcosystemWatch_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockEcosystemWatch_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *mockEcosystemWatch_Expecter) Stop() *mockEcosystemWatch_Stop_Call {
	return &mockEcosystemWatch_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *mockEcosystemWatch_Stop_Call) Run(run func()) *mockEcosystemWatch_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockEcosystemWatch_Stop_Call) Return() *mockEcosystemWatch_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockEcosystemWatch_Stop_Call) RunAndReturn(run func()) *mockEcosystemWatch_Stop_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockEcosystemWatch interface {
	mock.TestingT
	Cleanup(func())
}

// newMockEcosystemWatch creates a new instance of mockEcosystemWatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockEcosystemWatch(t mockConstructorTestingTnewMockEcosystemWatch) *mockEcosystemWatch {
	mock := &mockEcosystemWatch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
