// Code generated by mockery v2.53.5. DO NOT EDIT.

package velero

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: namespace, name
func (_m *MockService) Update(namespace string, name string) {
	_m.Called(namespace, name)
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - namespace string
//   - name string
func (_e *MockService_Expecter) Update(namespace interface{}, name interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", namespace, name)}
}

func (_c *MockService_Update_Call) Run(run func(namespace string, name string)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockService_Update_Call) Return() *MockService_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(string, string)) *MockService_Update_Call {
	_c.Run(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
