# permissions for end users to edit backupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: backupschedule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-backup-operator
    app.kubernetes.io/part-of: k8s-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupschedule-editor-role
rules:
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backupschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - k8s.cloudogu.com
  resources:
    - backupschedules/finalizers
  verbs:
    - update
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backupschedules/status
  verbs:
  - get
  - patch
  - update
