# permissions for end users to view backupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: backupschedule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-backup-operator
    app.kubernetes.io/part-of: k8s-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupschedule-viewer-role
rules:
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backupschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backupschedules/status
  verbs:
  - get
