---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-cluster-role
rules:
  # The operator needs this permission to clean up all resources before a restore.
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - delete
      - update