# permissions for end users to edit backupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: cronjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-backup-operator
    app.kubernetes.io/part-of: k8s-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-editor-role
rules:
- apiGroups:
  - "*"
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
