# permissions for end users to edit restores.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: restore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-backup-operator
    app.kubernetes.io/part-of: k8s-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: restore-editor-role
rules:
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - restores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - restore/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - restores/status
    verbs:
      - get
      - patch
      - update
