# permissions for end users to view restores.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: restore-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-backup-operator
    app.kubernetes.io/part-of: k8s-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: restore-viewer-role
rules:
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - restores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - restores/status
  verbs:
  - get
