---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-additional-role
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
