// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockMaintenanceGateway is an autogenerated mock type for the maintenanceGateway type
type mockMaintenanceGateway struct {
	mock.Mock
}

type mockMaintenanceGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMaintenanceGateway) EXPECT() *mockMaintenanceGateway_Expecter {
	return &mockMaintenanceGateway_Expecter{mock: &_m.Mock}
}

// ActivateMaintenance provides a mock function with given fields: ctx, title, text
func (_m *mockMaintenanceGateway) ActivateMaintenance(ctx context.Context, title string, text string) error {
	ret := _m.Called(ctx, title, text)

	if len(ret) == 0 {
		panic("no return value specified for ActivateMaintenance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, title, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMaintenanceGateway_ActivateMaintenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateMaintenance'
type mockMaintenanceGateway_ActivateMaintenance_Call struct {
	*mock.Call
}

// ActivateMaintenance is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - text string
func (_e *mockMaintenanceGateway_Expecter) ActivateMaintenance(ctx interface{}, title interface{}, text interface{}) *mockMaintenanceGateway_ActivateMaintenance_Call {
	return &mockMaintenanceGateway_ActivateMaintenance_Call{Call: _e.mock.On("ActivateMaintenance", ctx, title, text)}
}

func (_c *mockMaintenanceGateway_ActivateMaintenance_Call) Run(run func(ctx context.Context, title string, text string)) *mockMaintenanceGateway_ActivateMaintenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockMaintenanceGateway_ActivateMaintenance_Call) Return(_a0 error) *mockMaintenanceGateway_ActivateMaintenance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMaintenanceGateway_ActivateMaintenance_Call) RunAndReturn(run func(context.Context, string, string) error) *mockMaintenanceGateway_ActivateMaintenance_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMaintenanceGateway creates a new instance of mockMaintenanceGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMaintenanceGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMaintenanceGateway {
	mock := &mockMaintenanceGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
