// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockBlueprintGateway is an autogenerated mock type for the blueprintGateway type
type mockBlueprintGateway struct {
	mock.Mock
}

type mockBlueprintGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBlueprintGateway) EXPECT() *mockBlueprintGateway_Expecter {
	return &mockBlueprintGateway_Expecter{mock: &_m.Mock}
}

// find provides a mock function with given fields: _a0
func (_m *mockBlueprintGateway) find(_a0 context.Context) (*Blueprint, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for find")
	}

	var r0 *Blueprint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*Blueprint, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *Blueprint); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Blueprint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBlueprintGateway_find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'find'
type mockBlueprintGateway_find_Call struct {
	*mock.Call
}

// find is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockBlueprintGateway_Expecter) find(_a0 interface{}) *mockBlueprintGateway_find_Call {
	return &mockBlueprintGateway_find_Call{Call: _e.mock.On("find", _a0)}
}

func (_c *mockBlueprintGateway_find_Call) Run(run func(_a0 context.Context)) *mockBlueprintGateway_find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockBlueprintGateway_find_Call) Return(_a0 *Blueprint, _a1 error) *mockBlueprintGateway_find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBlueprintGateway_find_Call) RunAndReturn(run func(context.Context) (*Blueprint, error)) *mockBlueprintGateway_find_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBlueprintGateway creates a new instance of mockBlueprintGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBlueprintGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBlueprintGateway {
	mock := &mockBlueprintGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
