// Code generated by mockery v2.20.0. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-operator/pkg/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockBackupControllerManager is an autogenerated mock type for the backupControllerManager type
type mockBackupControllerManager struct {
	mock.Mock
}

type mockBackupControllerManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBackupControllerManager) EXPECT() *mockBackupControllerManager_Expecter {
	return &mockBackupControllerManager_Expecter{mock: &_m.Mock}
}

// create provides a mock function with given fields: ctx, backup
func (_m *mockBackupControllerManager) create(ctx context.Context, backup *v1.Backup) error {
	ret := _m.Called(ctx, backup)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) error); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBackupControllerManager_create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'create'
type mockBackupControllerManager_create_Call struct {
	*mock.Call
}

// create is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockBackupControllerManager_Expecter) create(ctx interface{}, backup interface{}) *mockBackupControllerManager_create_Call {
	return &mockBackupControllerManager_create_Call{Call: _e.mock.On("create", ctx, backup)}
}

func (_c *mockBackupControllerManager_create_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockBackupControllerManager_create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockBackupControllerManager_create_Call) Return(_a0 error) *mockBackupControllerManager_create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBackupControllerManager_create_Call) RunAndReturn(run func(context.Context, *v1.Backup) error) *mockBackupControllerManager_create_Call {
	_c.Call.Return(run)
	return _c
}

// delete provides a mock function with given fields: ctx, backup
func (_m *mockBackupControllerManager) delete(ctx context.Context, backup *v1.Backup) error {
	ret := _m.Called(ctx, backup)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) error); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBackupControllerManager_delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'delete'
type mockBackupControllerManager_delete_Call struct {
	*mock.Call
}

// delete is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockBackupControllerManager_Expecter) delete(ctx interface{}, backup interface{}) *mockBackupControllerManager_delete_Call {
	return &mockBackupControllerManager_delete_Call{Call: _e.mock.On("delete", ctx, backup)}
}

func (_c *mockBackupControllerManager_delete_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockBackupControllerManager_delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockBackupControllerManager_delete_Call) Return(_a0 error) *mockBackupControllerManager_delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBackupControllerManager_delete_Call) RunAndReturn(run func(context.Context, *v1.Backup) error) *mockBackupControllerManager_delete_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockBackupControllerManager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockBackupControllerManager creates a new instance of mockBackupControllerManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockBackupControllerManager(t mockConstructorTestingTnewMockBackupControllerManager) *mockBackupControllerManager {
	mock := &mockBackupControllerManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
