// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// createBackup provides a mock function with given fields: _a0, backup
func (_m *MockService) createBackup(_a0 context.Context, backup Backup) error {
	ret := _m.Called(_a0, backup)

	if len(ret) == 0 {
		panic("no return value specified for createBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Backup) error); ok {
		r0 = rf(_a0, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_createBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createBackup'
type MockService_createBackup_Call struct {
	*mock.Call
}

// createBackup is a helper method to define mock.On call
//   - _a0 context.Context
//   - backup Backup
func (_e *MockService_Expecter) createBackup(_a0 interface{}, backup interface{}) *MockService_createBackup_Call {
	return &MockService_createBackup_Call{Call: _e.mock.On("createBackup", _a0, backup)}
}

func (_c *MockService_createBackup_Call) Run(run func(_a0 context.Context, backup Backup)) *MockService_createBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Backup))
	})
	return _c
}

func (_c *MockService_createBackup_Call) Return(_a0 error) *MockService_createBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_createBackup_Call) RunAndReturn(run func(context.Context, Backup) error) *MockService_createBackup_Call {
	_c.Call.Return(run)
	return _c
}

// deleteBackup provides a mock function with given fields: _a0, backup
func (_m *MockService) deleteBackup(_a0 context.Context, backup Backup) error {
	ret := _m.Called(_a0, backup)

	if len(ret) == 0 {
		panic("no return value specified for deleteBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Backup) error); ok {
		r0 = rf(_a0, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_deleteBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deleteBackup'
type MockService_deleteBackup_Call struct {
	*mock.Call
}

// deleteBackup is a helper method to define mock.On call
//   - _a0 context.Context
//   - backup Backup
func (_e *MockService_Expecter) deleteBackup(_a0 interface{}, backup interface{}) *MockService_deleteBackup_Call {
	return &MockService_deleteBackup_Call{Call: _e.mock.On("deleteBackup", _a0, backup)}
}

func (_c *MockService_deleteBackup_Call) Run(run func(_a0 context.Context, backup Backup)) *MockService_deleteBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Backup))
	})
	return _c
}

func (_c *MockService_deleteBackup_Call) Return(_a0 error) *MockService_deleteBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_deleteBackup_Call) RunAndReturn(run func(context.Context, Backup) error) *MockService_deleteBackup_Call {
	_c.Call.Return(run)
	return _c
}

// markBackupAsNotFinishedInTime provides a mock function with given fields: _a0, backup
func (_m *MockService) markBackupAsNotFinishedInTime(_a0 context.Context, backup Backup) error {
	ret := _m.Called(_a0, backup)

	if len(ret) == 0 {
		panic("no return value specified for markBackupAsNotFinishedInTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Backup) error); ok {
		r0 = rf(_a0, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_markBackupAsNotFinishedInTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'markBackupAsNotFinishedInTime'
type MockService_markBackupAsNotFinishedInTime_Call struct {
	*mock.Call
}

// markBackupAsNotFinishedInTime is a helper method to define mock.On call
//   - _a0 context.Context
//   - backup Backup
func (_e *MockService_Expecter) markBackupAsNotFinishedInTime(_a0 interface{}, backup interface{}) *MockService_markBackupAsNotFinishedInTime_Call {
	return &MockService_markBackupAsNotFinishedInTime_Call{Call: _e.mock.On("markBackupAsNotFinishedInTime", _a0, backup)}
}

func (_c *MockService_markBackupAsNotFinishedInTime_Call) Run(run func(_a0 context.Context, backup Backup)) *MockService_markBackupAsNotFinishedInTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Backup))
	})
	return _c
}

func (_c *MockService_markBackupAsNotFinishedInTime_Call) Return(_a0 error) *MockService_markBackupAsNotFinishedInTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_markBackupAsNotFinishedInTime_Call) RunAndReturn(run func(context.Context, Backup) error) *MockService_markBackupAsNotFinishedInTime_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
