// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockTimeoutManager is an autogenerated mock type for the timeoutManager type
type mockTimeoutManager struct {
	mock.Mock
}

type mockTimeoutManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTimeoutManager) EXPECT() *mockTimeoutManager_Expecter {
	return &mockTimeoutManager_Expecter{mock: &_m.Mock}
}

// timeout provides a mock function with given fields: ctx, backup
func (_m *mockTimeoutManager) timeout(ctx context.Context, backup *v1.Backup) error {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for timeout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) error); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockTimeoutManager_timeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'timeout'
type mockTimeoutManager_timeout_Call struct {
	*mock.Call
}

// timeout is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockTimeoutManager_Expecter) timeout(ctx interface{}, backup interface{}) *mockTimeoutManager_timeout_Call {
	return &mockTimeoutManager_timeout_Call{Call: _e.mock.On("timeout", ctx, backup)}
}

func (_c *mockTimeoutManager_timeout_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockTimeoutManager_timeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockTimeoutManager_timeout_Call) Return(_a0 error) *mockTimeoutManager_timeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTimeoutManager_timeout_Call) RunAndReturn(run func(context.Context, *v1.Backup) error) *mockTimeoutManager_timeout_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTimeoutManager creates a new instance of mockTimeoutManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTimeoutManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTimeoutManager {
	mock := &mockTimeoutManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
