// Code generated by mockery v2.53.3. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockStatusSyncManager is an autogenerated mock type for the statusSyncManager type
type mockStatusSyncManager struct {
	mock.Mock
}

type mockStatusSyncManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStatusSyncManager) EXPECT() *mockStatusSyncManager_Expecter {
	return &mockStatusSyncManager_Expecter{mock: &_m.Mock}
}

// syncStatus provides a mock function with given fields: ctx, backup
func (_m *mockStatusSyncManager) syncStatus(ctx context.Context, backup *v1.Backup) error {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for syncStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) error); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusSyncManager_syncStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'syncStatus'
type mockStatusSyncManager_syncStatus_Call struct {
	*mock.Call
}

// syncStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockStatusSyncManager_Expecter) syncStatus(ctx interface{}, backup interface{}) *mockStatusSyncManager_syncStatus_Call {
	return &mockStatusSyncManager_syncStatus_Call{Call: _e.mock.On("syncStatus", ctx, backup)}
}

func (_c *mockStatusSyncManager_syncStatus_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockStatusSyncManager_syncStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockStatusSyncManager_syncStatus_Call) Return(_a0 error) *mockStatusSyncManager_syncStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusSyncManager_syncStatus_Call) RunAndReturn(run func(context.Context, *v1.Backup) error) *mockStatusSyncManager_syncStatus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStatusSyncManager creates a new instance of mockStatusSyncManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStatusSyncManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStatusSyncManager {
	mock := &mockStatusSyncManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
