// Code generated by mockery v2.53.5. DO NOT EDIT.

package cleanup

import (
	context "context"
	sync "sync"

	mock "github.com/stretchr/testify/mock"
)

// mockDoguManager is an autogenerated mock type for the doguManager type
type mockDoguManager struct {
	mock.Mock
}

type mockDoguManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguManager) EXPECT() *mockDoguManager_Expecter {
	return &mockDoguManager_Expecter{mock: &_m.Mock}
}

// cleanupDogus provides a mock function with given fields: ctx, wg
func (_m *mockDoguManager) cleanupDogus(ctx context.Context, wg *sync.WaitGroup) error {
	ret := _m.Called(ctx, wg)

	if len(ret) == 0 {
		panic("no return value specified for cleanupDogus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sync.WaitGroup) error); ok {
		r0 = rf(ctx, wg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguManager_cleanupDogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'cleanupDogus'
type mockDoguManager_cleanupDogus_Call struct {
	*mock.Call
}

// cleanupDogus is a helper method to define mock.On call
//   - ctx context.Context
//   - wg *sync.WaitGroup
func (_e *mockDoguManager_Expecter) cleanupDogus(ctx interface{}, wg interface{}) *mockDoguManager_cleanupDogus_Call {
	return &mockDoguManager_cleanupDogus_Call{Call: _e.mock.On("cleanupDogus", ctx, wg)}
}

func (_c *mockDoguManager_cleanupDogus_Call) Run(run func(ctx context.Context, wg *sync.WaitGroup)) *mockDoguManager_cleanupDogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sync.WaitGroup))
	})
	return _c
}

func (_c *mockDoguManager_cleanupDogus_Call) Return(_a0 error) *mockDoguManager_cleanupDogus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguManager_cleanupDogus_Call) RunAndReturn(run func(context.Context, *sync.WaitGroup) error) *mockDoguManager_cleanupDogus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguManager creates a new instance of mockDoguManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguManager {
	mock := &mockDoguManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
