// Code generated by mockery v2.53.5. DO NOT EDIT.

package cleanup

import (
	context "context"
	sync "sync"

	mock "github.com/stretchr/testify/mock"
)

// mockAdditionalResourceManager is an autogenerated mock type for the additionalResourceManager type
type mockAdditionalResourceManager struct {
	mock.Mock
}

type mockAdditionalResourceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAdditionalResourceManager) EXPECT() *mockAdditionalResourceManager_Expecter {
	return &mockAdditionalResourceManager_Expecter{mock: &_m.Mock}
}

// cleanupAdditionalResources provides a mock function with given fields: ctx, wg
func (_m *mockAdditionalResourceManager) cleanupAdditionalResources(ctx context.Context, wg *sync.WaitGroup) error {
	ret := _m.Called(ctx, wg)

	if len(ret) == 0 {
		panic("no return value specified for cleanupAdditionalResources")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sync.WaitGroup) error); ok {
		r0 = rf(ctx, wg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockAdditionalResourceManager_cleanupAdditionalResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'cleanupAdditionalResources'
type mockAdditionalResourceManager_cleanupAdditionalResources_Call struct {
	*mock.Call
}

// cleanupAdditionalResources is a helper method to define mock.On call
//   - ctx context.Context
//   - wg *sync.WaitGroup
func (_e *mockAdditionalResourceManager_Expecter) cleanupAdditionalResources(ctx interface{}, wg interface{}) *mockAdditionalResourceManager_cleanupAdditionalResources_Call {
	return &mockAdditionalResourceManager_cleanupAdditionalResources_Call{Call: _e.mock.On("cleanupAdditionalResources", ctx, wg)}
}

func (_c *mockAdditionalResourceManager_cleanupAdditionalResources_Call) Run(run func(ctx context.Context, wg *sync.WaitGroup)) *mockAdditionalResourceManager_cleanupAdditionalResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sync.WaitGroup))
	})
	return _c
}

func (_c *mockAdditionalResourceManager_cleanupAdditionalResources_Call) Return(_a0 error) *mockAdditionalResourceManager_cleanupAdditionalResources_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAdditionalResourceManager_cleanupAdditionalResources_Call) RunAndReturn(run func(context.Context, *sync.WaitGroup) error) *mockAdditionalResourceManager_cleanupAdditionalResources_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAdditionalResourceManager creates a new instance of mockAdditionalResourceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAdditionalResourceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAdditionalResourceManager {
	mock := &mockAdditionalResourceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
