apiVersion: k8s.cloudogu.com/v1
kind: BackupSchedule
metadata:
  labels:
    app.kubernetes.io/name: backupschedule
    app.kubernetes.io/instance: backupschedule-sample
    app.kubernetes.io/part-of: k8s-backup-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-backup-operator
  name: backupschedule-sample
spec:
  schedule: "0 0 * * *"
  provider: "velero"
