apiVersion: k8s.cloudogu.com/v1
kind: Restore
metadata:
  labels:
    app.kubernetes.io/name: restore
    app.kubernetes.io/instance: restore-sample
    app.kubernetes.io/part-of: kubebuilder-backup-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-backup-operator
  name: restore-sample
spec:
  # TODO(user): Add fields here
