apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mailpit-ingress
  namespace: ecosystem
spec:
  podSelector:
    matchLabels:
      app: mailpit # Targets your Mailpit pod
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ecosystem
      ports:
        - protocol: TCP
          port: 8025
        - protocol: TCP
          port: 1025