// Code generated by mockery v2.42.1. DO NOT EDIT.

package backupschedule

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-operator/pkg/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// create provides a mock function with given fields: ctx, backupSchedule
func (_m *MockManager) create(ctx context.Context, backupSchedule *v1.BackupSchedule) error {
	ret := _m.Called(ctx, backupSchedule)

	if len(ret) == 0 {
		panic("no return value specified for create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule) error); ok {
		r0 = rf(ctx, backupSchedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'create'
type MockManager_create_Call struct {
	*mock.Call
}

// create is a helper method to define mock.On call
//   - ctx context.Context
//   - backupSchedule *v1.BackupSchedule
func (_e *MockManager_Expecter) create(ctx interface{}, backupSchedule interface{}) *MockManager_create_Call {
	return &MockManager_create_Call{Call: _e.mock.On("create", ctx, backupSchedule)}
}

func (_c *MockManager_create_Call) Run(run func(ctx context.Context, backupSchedule *v1.BackupSchedule)) *MockManager_create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *MockManager_create_Call) Return(_a0 error) *MockManager_create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_create_Call) RunAndReturn(run func(context.Context, *v1.BackupSchedule) error) *MockManager_create_Call {
	_c.Call.Return(run)
	return _c
}

// delete provides a mock function with given fields: ctx, backupSchedule
func (_m *MockManager) delete(ctx context.Context, backupSchedule *v1.BackupSchedule) error {
	ret := _m.Called(ctx, backupSchedule)

	if len(ret) == 0 {
		panic("no return value specified for delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule) error); ok {
		r0 = rf(ctx, backupSchedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'delete'
type MockManager_delete_Call struct {
	*mock.Call
}

// delete is a helper method to define mock.On call
//   - ctx context.Context
//   - backupSchedule *v1.BackupSchedule
func (_e *MockManager_Expecter) delete(ctx interface{}, backupSchedule interface{}) *MockManager_delete_Call {
	return &MockManager_delete_Call{Call: _e.mock.On("delete", ctx, backupSchedule)}
}

func (_c *MockManager_delete_Call) Run(run func(ctx context.Context, backupSchedule *v1.BackupSchedule)) *MockManager_delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *MockManager_delete_Call) Return(_a0 error) *MockManager_delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_delete_Call) RunAndReturn(run func(context.Context, *v1.BackupSchedule) error) *MockManager_delete_Call {
	_c.Call.Return(run)
	return _c
}

// update provides a mock function with given fields: ctx, backupSchedule
func (_m *MockManager) update(ctx context.Context, backupSchedule *v1.BackupSchedule) error {
	ret := _m.Called(ctx, backupSchedule)

	if len(ret) == 0 {
		panic("no return value specified for update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule) error); ok {
		r0 = rf(ctx, backupSchedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'update'
type MockManager_update_Call struct {
	*mock.Call
}

// update is a helper method to define mock.On call
//   - ctx context.Context
//   - backupSchedule *v1.BackupSchedule
func (_e *MockManager_Expecter) update(ctx interface{}, backupSchedule interface{}) *MockManager_update_Call {
	return &MockManager_update_Call{Call: _e.mock.On("update", ctx, backupSchedule)}
}

func (_c *MockManager_update_Call) Run(run func(ctx context.Context, backupSchedule *v1.BackupSchedule)) *MockManager_update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.BackupSchedule))
	})
	return _c
}

func (_c *MockManager_update_Call) Return(_a0 error) *MockManager_update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_update_Call) RunAndReturn(run func(context.Context, *v1.BackupSchedule) error) *MockManager_update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
