apiVersion: v1

values:
  images:
    backup-operator: cloudogu/k8s-backup-operator:0.8.0
    kube-rbac-proxy: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1

patches:
  values.yaml:
    additionalImages:
    kubeRbacProxy:
      image:
        repository: "{{ registryFrom .images.kube-rbac-proxy }}/{{ repositoryFrom .images.kube-rbac-proxy }}"
        tag: "{{ tagFrom .images.kube-rbac-proxy }}"
    manager:
      image:
        repository: "{{ registryFrom .images.backup-operator }}/{{ repositoryFrom .images.backup-operator }}"
        tag: "{{ tagFrom .images.backup-operator }}"