apiVersion: v1
values:
  images:
    backupOperator: cloudogu/k8s-backup-operator:0.10.1
    kubeRbacProxy: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
patches:
  values.yaml:
    kubeRbacProxy:
      image:
        repository: "{{ registryFrom .images.kubeRbacProxy }}/{{ repositoryFrom .images.kubeRbacProxy }}"
        tag: "{{ tagFrom .images.kubeRbacProxy }}"
    manager:
      image:
        repository: "{{ registryFrom .images.backupOperator }}/{{ repositoryFrom .images.backupOperator }}"
        tag: "{{ tagFrom .images.backupOperator }}"
