apiVersion: v1
values:
  images:
    backupOperator: cloudogu/k8s-backup-operator:1.1.1
    kubeRbacProxy: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
patches:
  values.yaml:
    kubeRbacProxy:
      image:
        registry: "{{ registryFrom .images.kubeRbacProxy }}"
        repository: "{{ repositoryFrom .images.kubeRbacProxy }}"
        tag: "{{ tagFrom .images.kubeRbacProxy }}"
    manager:
      image:
        registry: "{{ registryFrom .images.backupOperator }}"
        repository: "{{ repositoryFrom .images.backupOperator }}"
        tag: "{{ tagFrom .images.backupOperator }}"
