apiVersion: v1
values:
  images:
    backupOperator: cloudogu/k8s-backup-operator:1.3.3
patches:
  values.yaml:
    manager:
      image:
        registry: "{{ registryFrom .images.backupOperator }}"
        repository: "{{ repositoryFrom .images.backupOperator }}"
        tag: "{{ tagFrom .images.backupOperator }}"
