apiVersion: v1

values:
  images:
    backup-operator: cloudogu/k8s-backup-operator:0.6.0
    kubectl: bitnami/kubectl:1.27.7
    kube-rbac-proxy: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1

patches:
  values.yaml:
    additionalImages:
      kubectl: "{{ registryFrom .images.kubectl }}/{{ repositoryFrom .images.kubectl }}:{{ tagFrom .images.kubectl }}"
#      TODO: Wait for conversion from kustomize to helm