apiVersion: v1
values:
  images:
    backupOperator: cloudogu/k8s-backup-operator:2.2.2
    kubectl: alpine/kubectl:1.34.1
patches:
  values.yaml:
    manager:
      image:
        registry: "{{ registryFrom .images.backupOperator }}"
        repository: "{{ repositoryFrom .images.backupOperator }}"
        tag: "{{ tagFrom .images.backupOperator }}"
    initContainer:
      image:
        registry: "{{ registryFrom .images.kubectl }}"
        repository: "{{ repositoryFrom .images.kubectl }}"
        tag: "{{ tagFrom .images.kubectl }}"
