global:
  imagePullSecrets:
    - name: "ces-container-registries"
  networkPolicies:
    enabled: true
retention:
  strategy: keepAll
  garbageCollectionCron: "0 * * * *"
cleanup:
  exclude: # group, version, kind, name
    - name: "ces-loadbalancer"
      kind: "Service"
      version: "*"
    - name: "ecosystem-certificate"
      kind: "Secret"
      version: "*"
    - name: "k8s-backup-operator"
      kind: "Component"
      version: "*"
      group: "k8s.cloudogu.com"
    - name: "k8s-backup-operator-crd"
      kind: "Component"
      version: "*"
      group: "k8s.cloudogu.com"
    - name: "k8s-snapshot-controller"
      kind: "Component"
      version: "*"
      group: "k8s.cloudogu.com"
    - name: "k8s-snapshot-controller-crd"
      kind: "Component"
      version: "*"
      group: "k8s.cloudogu.com"
    - name: "k8s-velero"
      kind: "Component"
      version: "*"
      group: "k8s.cloudogu.com"
manager:
  env:
    stage: production
    logLevel: info
  image:
    registry: docker.io
    repository: cloudogu/k8s-backup-operator
    tag: 1.4.2
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      memory: 105M
    requests:
      cpu: 15m
      memory: 105M
  replicas: 1
