global:
  imagePullSecrets:
    - name: "ces-container-registries"
  networkPolicies:
    enabled: true
retention:
  strategy: keepAll
  garbageCollectionCron: "0 * * * *"
cleanup:
  exclude: # group, version, kind, name
    - name: "ces-loadbalancer"
      kind: "Service"
manager:
  env:
    stage: production
    logLevel: info
  image:
    registry: docker.io
    repository: cloudogu/k8s-backup-operator
    tag: 1.3.4
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  replicas: 1
