global:
  imagePullSecrets:
    - name: "ces-container-registries"
retention:
  strategy: keepAll
  garbageCollectionCron: "0 * * * *"
kubeRbacProxy:
  image:
    registry: gcr.io
    repository: kubebuilder/kube-rbac-proxy
    tag: v0.14.1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
manager:
  env:
    stage: production
    logLevel: info
  image:
    registry: docker.io
    repository: cloudogu/k8s-backup-operator
    tag: 1.1.0
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  replicas: 1
