// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	v3 "github.com/cloudogu/k8s-blueprint-lib/v3/api/v3"
	mock "github.com/stretchr/testify/mock"
)

// mockService is an autogenerated mock type for the service type
type mockService struct {
	mock.Mock
}

type mockService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockService) EXPECT() *mockService_Expecter {
	return &mockService_Expecter{mock: &_m.Mock}
}

// addBlueprintAnnotation provides a mock function with given fields: _a0, backup, displayName, dogus
func (_m *mockService) addBlueprintAnnotation(_a0 context.Context, backup *v1.Backup, displayName string, dogus []v3.Dogu) error {
	ret := _m.Called(_a0, backup, displayName, dogus)

	if len(ret) == 0 {
		panic("no return value specified for addBlueprintAnnotation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, []v3.Dogu) error); ok {
		r0 = rf(_a0, backup, displayName, dogus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockService_addBlueprintAnnotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'addBlueprintAnnotation'
type mockService_addBlueprintAnnotation_Call struct {
	*mock.Call
}

// addBlueprintAnnotation is a helper method to define mock.On call
//   - _a0 context.Context
//   - backup *v1.Backup
//   - displayName string
//   - dogus []v3.Dogu
func (_e *mockService_Expecter) addBlueprintAnnotation(_a0 interface{}, backup interface{}, displayName interface{}, dogus interface{}) *mockService_addBlueprintAnnotation_Call {
	return &mockService_addBlueprintAnnotation_Call{Call: _e.mock.On("addBlueprintAnnotation", _a0, backup, displayName, dogus)}
}

func (_c *mockService_addBlueprintAnnotation_Call) Run(run func(_a0 context.Context, backup *v1.Backup, displayName string, dogus []v3.Dogu)) *mockService_addBlueprintAnnotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(string), args[3].([]v3.Dogu))
	})
	return _c
}

func (_c *mockService_addBlueprintAnnotation_Call) Return(_a0 error) *mockService_addBlueprintAnnotation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockService_addBlueprintAnnotation_Call) RunAndReturn(run func(context.Context, *v1.Backup, string, []v3.Dogu) error) *mockService_addBlueprintAnnotation_Call {
	_c.Call.Return(run)
	return _c
}

// cancelBackup provides a mock function with given fields: _a0, backup
func (_m *mockService) cancelBackup(_a0 context.Context, backup *v1.Backup) error {
	ret := _m.Called(_a0, backup)

	if len(ret) == 0 {
		panic("no return value specified for cancelBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) error); ok {
		r0 = rf(_a0, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockService_cancelBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'cancelBackup'
type mockService_cancelBackup_Call struct {
	*mock.Call
}

// cancelBackup is a helper method to define mock.On call
//   - _a0 context.Context
//   - backup *v1.Backup
func (_e *mockService_Expecter) cancelBackup(_a0 interface{}, backup interface{}) *mockService_cancelBackup_Call {
	return &mockService_cancelBackup_Call{Call: _e.mock.On("cancelBackup", _a0, backup)}
}

func (_c *mockService_cancelBackup_Call) Run(run func(_a0 context.Context, backup *v1.Backup)) *mockService_cancelBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockService_cancelBackup_Call) Return(_a0 error) *mockService_cancelBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockService_cancelBackup_Call) RunAndReturn(run func(context.Context, *v1.Backup) error) *mockService_cancelBackup_Call {
	_c.Call.Return(run)
	return _c
}

// configureBackup provides a mock function with given fields: _a0, backup
func (_m *mockService) configureBackup(_a0 context.Context, backup *v1.Backup) {
	_m.Called(_a0, backup)
}

// mockService_configureBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'configureBackup'
type mockService_configureBackup_Call struct {
	*mock.Call
}

// configureBackup is a helper method to define mock.On call
//   - _a0 context.Context
//   - backup *v1.Backup
func (_e *mockService_Expecter) configureBackup(_a0 interface{}, backup interface{}) *mockService_configureBackup_Call {
	return &mockService_configureBackup_Call{Call: _e.mock.On("configureBackup", _a0, backup)}
}

func (_c *mockService_configureBackup_Call) Run(run func(_a0 context.Context, backup *v1.Backup)) *mockService_configureBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockService_configureBackup_Call) Return() *mockService_configureBackup_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockService_configureBackup_Call) RunAndReturn(run func(context.Context, *v1.Backup)) *mockService_configureBackup_Call {
	_c.Run(run)
	return _c
}

// deleteBackup provides a mock function with given fields: _a0, backup
func (_m *mockService) deleteBackup(_a0 context.Context, backup *v1.Backup) error {
	ret := _m.Called(_a0, backup)

	if len(ret) == 0 {
		panic("no return value specified for deleteBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) error); ok {
		r0 = rf(_a0, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockService_deleteBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deleteBackup'
type mockService_deleteBackup_Call struct {
	*mock.Call
}

// deleteBackup is a helper method to define mock.On call
//   - _a0 context.Context
//   - backup *v1.Backup
func (_e *mockService_Expecter) deleteBackup(_a0 interface{}, backup interface{}) *mockService_deleteBackup_Call {
	return &mockService_deleteBackup_Call{Call: _e.mock.On("deleteBackup", _a0, backup)}
}

func (_c *mockService_deleteBackup_Call) Run(run func(_a0 context.Context, backup *v1.Backup)) *mockService_deleteBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockService_deleteBackup_Call) Return(_a0 error) *mockService_deleteBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockService_deleteBackup_Call) RunAndReturn(run func(context.Context, *v1.Backup) error) *mockService_deleteBackup_Call {
	_c.Call.Return(run)
	return _c
}

// reconcileBackup provides a mock function with given fields: _a0, backup
func (_m *mockService) reconcileBackup(_a0 context.Context, backup *v1.Backup) error {
	ret := _m.Called(_a0, backup)

	if len(ret) == 0 {
		panic("no return value specified for reconcileBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) error); ok {
		r0 = rf(_a0, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockService_reconcileBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'reconcileBackup'
type mockService_reconcileBackup_Call struct {
	*mock.Call
}

// reconcileBackup is a helper method to define mock.On call
//   - _a0 context.Context
//   - backup *v1.Backup
func (_e *mockService_Expecter) reconcileBackup(_a0 interface{}, backup interface{}) *mockService_reconcileBackup_Call {
	return &mockService_reconcileBackup_Call{Call: _e.mock.On("reconcileBackup", _a0, backup)}
}

func (_c *mockService_reconcileBackup_Call) Run(run func(_a0 context.Context, backup *v1.Backup)) *mockService_reconcileBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockService_reconcileBackup_Call) Return(_a0 error) *mockService_reconcileBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockService_reconcileBackup_Call) RunAndReturn(run func(context.Context, *v1.Backup) error) *mockService_reconcileBackup_Call {
	_c.Call.Return(run)
	return _c
}

// newMockService creates a new instance of mockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockService {
	mock := &mockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
