// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockStage is an autogenerated mock type for the stage type
type mockStage struct {
	mock.Mock
}

type mockStage_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStage) EXPECT() *mockStage_Expecter {
	return &mockStage_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, backup
func (_m *mockStage) Execute(ctx context.Context, backup *v1.Backup) (*v1.Backup, stageOutcome) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *v1.Backup
	var r1 stageOutcome
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, backup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) stageOutcome); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Get(1).(stageOutcome)
	}

	return r0, r1
}

// mockStage_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockStage_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockStage_Expecter) Execute(ctx interface{}, backup interface{}) *mockStage_Execute_Call {
	return &mockStage_Execute_Call{Call: _e.mock.On("Execute", ctx, backup)}
}

func (_c *mockStage_Execute_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockStage_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockStage_Execute_Call) Return(_a0 *v1.Backup, _a1 stageOutcome) *mockStage_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockStage_Execute_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)) *mockStage_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStage creates a new instance of mockStage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStage(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStage {
	mock := &mockStage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
