// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockMaintenanceGateway is an autogenerated mock type for the maintenanceGateway type
type mockMaintenanceGateway struct {
	mock.Mock
}

type mockMaintenanceGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMaintenanceGateway) EXPECT() *mockMaintenanceGateway_Expecter {
	return &mockMaintenanceGateway_Expecter{mock: &_m.Mock}
}

// activateMaintenanceMode provides a mock function with given fields: ctx, title, text
func (_m *mockMaintenanceGateway) activateMaintenanceMode(ctx context.Context, title string, text string) error {
	ret := _m.Called(ctx, title, text)

	if len(ret) == 0 {
		panic("no return value specified for activateMaintenanceMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, title, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMaintenanceGateway_activateMaintenanceMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'activateMaintenanceMode'
type mockMaintenanceGateway_activateMaintenanceMode_Call struct {
	*mock.Call
}

// activateMaintenanceMode is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - text string
func (_e *mockMaintenanceGateway_Expecter) activateMaintenanceMode(ctx interface{}, title interface{}, text interface{}) *mockMaintenanceGateway_activateMaintenanceMode_Call {
	return &mockMaintenanceGateway_activateMaintenanceMode_Call{Call: _e.mock.On("activateMaintenanceMode", ctx, title, text)}
}

func (_c *mockMaintenanceGateway_activateMaintenanceMode_Call) Run(run func(ctx context.Context, title string, text string)) *mockMaintenanceGateway_activateMaintenanceMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockMaintenanceGateway_activateMaintenanceMode_Call) Return(_a0 error) *mockMaintenanceGateway_activateMaintenanceMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMaintenanceGateway_activateMaintenanceMode_Call) RunAndReturn(run func(context.Context, string, string) error) *mockMaintenanceGateway_activateMaintenanceMode_Call {
	_c.Call.Return(run)
	return _c
}

// deactivateMaintenanceMode provides a mock function with given fields: ctx
func (_m *mockMaintenanceGateway) deactivateMaintenanceMode(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for deactivateMaintenanceMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMaintenanceGateway_deactivateMaintenanceMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deactivateMaintenanceMode'
type mockMaintenanceGateway_deactivateMaintenanceMode_Call struct {
	*mock.Call
}

// deactivateMaintenanceMode is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockMaintenanceGateway_Expecter) deactivateMaintenanceMode(ctx interface{}) *mockMaintenanceGateway_deactivateMaintenanceMode_Call {
	return &mockMaintenanceGateway_deactivateMaintenanceMode_Call{Call: _e.mock.On("deactivateMaintenanceMode", ctx)}
}

func (_c *mockMaintenanceGateway_deactivateMaintenanceMode_Call) Run(run func(ctx context.Context)) *mockMaintenanceGateway_deactivateMaintenanceMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockMaintenanceGateway_deactivateMaintenanceMode_Call) Return(_a0 error) *mockMaintenanceGateway_deactivateMaintenanceMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMaintenanceGateway_deactivateMaintenanceMode_Call) RunAndReturn(run func(context.Context) error) *mockMaintenanceGateway_deactivateMaintenanceMode_Call {
	_c.Call.Return(run)
	return _c
}

// isMaintenanceModeActive provides a mock function with given fields: ctx
func (_m *mockMaintenanceGateway) isMaintenanceModeActive(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for isMaintenanceModeActive")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMaintenanceGateway_isMaintenanceModeActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isMaintenanceModeActive'
type mockMaintenanceGateway_isMaintenanceModeActive_Call struct {
	*mock.Call
}

// isMaintenanceModeActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockMaintenanceGateway_Expecter) isMaintenanceModeActive(ctx interface{}) *mockMaintenanceGateway_isMaintenanceModeActive_Call {
	return &mockMaintenanceGateway_isMaintenanceModeActive_Call{Call: _e.mock.On("isMaintenanceModeActive", ctx)}
}

func (_c *mockMaintenanceGateway_isMaintenanceModeActive_Call) Run(run func(ctx context.Context)) *mockMaintenanceGateway_isMaintenanceModeActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockMaintenanceGateway_isMaintenanceModeActive_Call) Return(_a0 bool, _a1 error) *mockMaintenanceGateway_isMaintenanceModeActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMaintenanceGateway_isMaintenanceModeActive_Call) RunAndReturn(run func(context.Context) (bool, error)) *mockMaintenanceGateway_isMaintenanceModeActive_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMaintenanceGateway creates a new instance of mockMaintenanceGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMaintenanceGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMaintenanceGateway {
	mock := &mockMaintenanceGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
