// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	logr "github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
)

// mockReconciler is an autogenerated mock type for the reconciler type
type mockReconciler struct {
	mock.Mock
}

type mockReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockReconciler) EXPECT() *mockReconciler_Expecter {
	return &mockReconciler_Expecter{mock: &_m.Mock}
}

// ensureBackupIsCanceledAfterTimeWindowExpired provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureBackupIsCanceledAfterTimeWindowExpired(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureBackupIsCanceledAfterTimeWindowExpired")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureBackupIsCanceledAfterTimeWindowExpired'
type mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call struct {
	*mock.Call
}

// ensureBackupIsCanceledAfterTimeWindowExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureBackupIsCanceledAfterTimeWindowExpired(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call {
	return &mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call{Call: _e.mock.On("ensureBackupIsCanceledAfterTimeWindowExpired", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call {
	_c.Call.Return(run)
	return _c
}

// ensureBackupIsPrepared provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureBackupIsPrepared(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureBackupIsPrepared")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureBackupIsPrepared_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureBackupIsPrepared'
type mockReconciler_ensureBackupIsPrepared_Call struct {
	*mock.Call
}

// ensureBackupIsPrepared is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureBackupIsPrepared(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureBackupIsPrepared_Call {
	return &mockReconciler_ensureBackupIsPrepared_Call{Call: _e.mock.On("ensureBackupIsPrepared", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureBackupIsPrepared_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureBackupIsPrepared_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureBackupIsPrepared_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureBackupIsPrepared_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureBackupIsPrepared_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureBackupIsPrepared_Call {
	_c.Call.Return(run)
	return _c
}

// ensureBackupSetup provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureBackupSetup(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureBackupSetup")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureBackupSetup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureBackupSetup'
type mockReconciler_ensureBackupSetup_Call struct {
	*mock.Call
}

// ensureBackupSetup is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureBackupSetup(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureBackupSetup_Call {
	return &mockReconciler_ensureBackupSetup_Call{Call: _e.mock.On("ensureBackupSetup", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureBackupSetup_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureBackupSetup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureBackupSetup_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureBackupSetup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureBackupSetup_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureBackupSetup_Call {
	_c.Call.Return(run)
	return _c
}

// ensureCompletedBackupIsIgnored provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureCompletedBackupIsIgnored(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureCompletedBackupIsIgnored")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureCompletedBackupIsIgnored_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureCompletedBackupIsIgnored'
type mockReconciler_ensureCompletedBackupIsIgnored_Call struct {
	*mock.Call
}

// ensureCompletedBackupIsIgnored is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureCompletedBackupIsIgnored(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureCompletedBackupIsIgnored_Call {
	return &mockReconciler_ensureCompletedBackupIsIgnored_Call{Call: _e.mock.On("ensureCompletedBackupIsIgnored", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureCompletedBackupIsIgnored_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureCompletedBackupIsIgnored_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureCompletedBackupIsIgnored_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureCompletedBackupIsIgnored_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureCompletedBackupIsIgnored_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureCompletedBackupIsIgnored_Call {
	_c.Call.Return(run)
	return _c
}

// ensureMaintenanceActivated provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureMaintenanceActivated(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureMaintenanceActivated")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureMaintenanceActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureMaintenanceActivated'
type mockReconciler_ensureMaintenanceActivated_Call struct {
	*mock.Call
}

// ensureMaintenanceActivated is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureMaintenanceActivated(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureMaintenanceActivated_Call {
	return &mockReconciler_ensureMaintenanceActivated_Call{Call: _e.mock.On("ensureMaintenanceActivated", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureMaintenanceActivated_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureMaintenanceActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureMaintenanceActivated_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureMaintenanceActivated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureMaintenanceActivated_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureMaintenanceActivated_Call {
	_c.Call.Return(run)
	return _c
}

// ensureMaintenanceDeactivated provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureMaintenanceDeactivated(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureMaintenanceDeactivated")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureMaintenanceDeactivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureMaintenanceDeactivated'
type mockReconciler_ensureMaintenanceDeactivated_Call struct {
	*mock.Call
}

// ensureMaintenanceDeactivated is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureMaintenanceDeactivated(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureMaintenanceDeactivated_Call {
	return &mockReconciler_ensureMaintenanceDeactivated_Call{Call: _e.mock.On("ensureMaintenanceDeactivated", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureMaintenanceDeactivated_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureMaintenanceDeactivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureMaintenanceDeactivated_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureMaintenanceDeactivated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureMaintenanceDeactivated_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureMaintenanceDeactivated_Call {
	_c.Call.Return(run)
	return _c
}

// ensureProviderBackupCompleted provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureProviderBackupCompleted(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureProviderBackupCompleted")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureProviderBackupCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureProviderBackupCompleted'
type mockReconciler_ensureProviderBackupCompleted_Call struct {
	*mock.Call
}

// ensureProviderBackupCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureProviderBackupCompleted(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureProviderBackupCompleted_Call {
	return &mockReconciler_ensureProviderBackupCompleted_Call{Call: _e.mock.On("ensureProviderBackupCompleted", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureProviderBackupCompleted_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureProviderBackupCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureProviderBackupCompleted_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureProviderBackupCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureProviderBackupCompleted_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureProviderBackupCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// ensureProviderBackupCreated provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureProviderBackupCreated(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureProviderBackupCreated")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureProviderBackupCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureProviderBackupCreated'
type mockReconciler_ensureProviderBackupCreated_Call struct {
	*mock.Call
}

// ensureProviderBackupCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureProviderBackupCreated(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureProviderBackupCreated_Call {
	return &mockReconciler_ensureProviderBackupCreated_Call{Call: _e.mock.On("ensureProviderBackupCreated", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureProviderBackupCreated_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureProviderBackupCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureProviderBackupCreated_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureProviderBackupCreated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureProviderBackupCreated_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureProviderBackupCreated_Call {
	_c.Call.Return(run)
	return _c
}

// ensureProviderBackupDeleted provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureProviderBackupDeleted(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureProviderBackupDeleted")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureProviderBackupDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureProviderBackupDeleted'
type mockReconciler_ensureProviderBackupDeleted_Call struct {
	*mock.Call
}

// ensureProviderBackupDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureProviderBackupDeleted(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureProviderBackupDeleted_Call {
	return &mockReconciler_ensureProviderBackupDeleted_Call{Call: _e.mock.On("ensureProviderBackupDeleted", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureProviderBackupDeleted_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureProviderBackupDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureProviderBackupDeleted_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureProviderBackupDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureProviderBackupDeleted_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureProviderBackupDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// ensureVeleroStatusSynced provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) ensureVeleroStatusSynced(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for ensureVeleroStatusSynced")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureVeleroStatusSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureVeleroStatusSynced'
type mockReconciler_ensureVeleroStatusSynced_Call struct {
	*mock.Call
}

// ensureVeleroStatusSynced is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) ensureVeleroStatusSynced(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_ensureVeleroStatusSynced_Call {
	return &mockReconciler_ensureVeleroStatusSynced_Call{Call: _e.mock.On("ensureVeleroStatusSynced", ctx, backup, logger)}
}

func (_c *mockReconciler_ensureVeleroStatusSynced_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_ensureVeleroStatusSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_ensureVeleroStatusSynced_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureVeleroStatusSynced_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureVeleroStatusSynced_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_ensureVeleroStatusSynced_Call {
	_c.Call.Return(run)
	return _c
}

// newMockReconciler creates a new instance of mockReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockReconciler {
	mock := &mockReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
