// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	logr "github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
)

// mockEnsureFunction is an autogenerated mock type for the ensureFunction type
type mockEnsureFunction struct {
	mock.Mock
}

type mockEnsureFunction_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEnsureFunction) EXPECT() *mockEnsureFunction_Expecter {
	return &mockEnsureFunction_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, backup, logger
func (_m *mockEnsureFunction) Execute(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockEnsureFunction_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockEnsureFunction_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockEnsureFunction_Expecter) Execute(ctx interface{}, backup interface{}, logger interface{}) *mockEnsureFunction_Execute_Call {
	return &mockEnsureFunction_Execute_Call{Call: _e.mock.On("Execute", ctx, backup, logger)}
}

func (_c *mockEnsureFunction_Execute_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockEnsureFunction_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockEnsureFunction_Execute_Call) Return(_a0 action, _a1 error) *mockEnsureFunction_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockEnsureFunction_Execute_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockEnsureFunction_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockEnsureFunction creates a new instance of mockEnsureFunction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEnsureFunction(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEnsureFunction {
	mock := &mockEnsureFunction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
