// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockReconciler is an autogenerated mock type for the reconciler type
type mockReconciler struct {
	mock.Mock
}

type mockReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockReconciler) EXPECT() *mockReconciler_Expecter {
	return &mockReconciler_Expecter{mock: &_m.Mock}
}

// ensureActiveBackupLease provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureActiveBackupLease(ctx context.Context, backup *v1.Backup) (*v1.Backup, stageOutcome) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureActiveBackupLease")
	}

	var r0 *v1.Backup
	var r1 stageOutcome
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, backup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) stageOutcome); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Get(1).(stageOutcome)
	}

	return r0, r1
}

// mockReconciler_ensureActiveBackupLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureActiveBackupLease'
type mockReconciler_ensureActiveBackupLease_Call struct {
	*mock.Call
}

// ensureActiveBackupLease is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureActiveBackupLease(ctx interface{}, backup interface{}) *mockReconciler_ensureActiveBackupLease_Call {
	return &mockReconciler_ensureActiveBackupLease_Call{Call: _e.mock.On("ensureActiveBackupLease", ctx, backup)}
}

func (_c *mockReconciler_ensureActiveBackupLease_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureActiveBackupLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureActiveBackupLease_Call) Return(_a0 *v1.Backup, _a1 stageOutcome) *mockReconciler_ensureActiveBackupLease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureActiveBackupLease_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)) *mockReconciler_ensureActiveBackupLease_Call {
	_c.Call.Return(run)
	return _c
}

// ensureBackupIsCanceledAfterTimeWindowExpired provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureBackupIsCanceledAfterTimeWindowExpired(ctx context.Context, backup *v1.Backup) (*v1.Backup, stageOutcome) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureBackupIsCanceledAfterTimeWindowExpired")
	}

	var r0 *v1.Backup
	var r1 stageOutcome
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, backup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) stageOutcome); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Get(1).(stageOutcome)
	}

	return r0, r1
}

// mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureBackupIsCanceledAfterTimeWindowExpired'
type mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call struct {
	*mock.Call
}

// ensureBackupIsCanceledAfterTimeWindowExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureBackupIsCanceledAfterTimeWindowExpired(ctx interface{}, backup interface{}) *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call {
	return &mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call{Call: _e.mock.On("ensureBackupIsCanceledAfterTimeWindowExpired", ctx, backup)}
}

func (_c *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call) Return(_a0 *v1.Backup, _a1 stageOutcome) *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)) *mockReconciler_ensureBackupIsCanceledAfterTimeWindowExpired_Call {
	_c.Call.Return(run)
	return _c
}

// ensureBackupIsPrepared provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureBackupIsPrepared(ctx context.Context, backup *v1.Backup) (*v1.Backup, stageOutcome) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureBackupIsPrepared")
	}

	var r0 *v1.Backup
	var r1 stageOutcome
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, backup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) stageOutcome); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Get(1).(stageOutcome)
	}

	return r0, r1
}

// mockReconciler_ensureBackupIsPrepared_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureBackupIsPrepared'
type mockReconciler_ensureBackupIsPrepared_Call struct {
	*mock.Call
}

// ensureBackupIsPrepared is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureBackupIsPrepared(ctx interface{}, backup interface{}) *mockReconciler_ensureBackupIsPrepared_Call {
	return &mockReconciler_ensureBackupIsPrepared_Call{Call: _e.mock.On("ensureBackupIsPrepared", ctx, backup)}
}

func (_c *mockReconciler_ensureBackupIsPrepared_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureBackupIsPrepared_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureBackupIsPrepared_Call) Return(_a0 *v1.Backup, _a1 stageOutcome) *mockReconciler_ensureBackupIsPrepared_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureBackupIsPrepared_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)) *mockReconciler_ensureBackupIsPrepared_Call {
	_c.Call.Return(run)
	return _c
}

// ensureBackupLeaseReleased provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureBackupLeaseReleased(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureBackupLeaseReleased")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureBackupLeaseReleased_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureBackupLeaseReleased'
type mockReconciler_ensureBackupLeaseReleased_Call struct {
	*mock.Call
}

// ensureBackupLeaseReleased is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureBackupLeaseReleased(ctx interface{}, backup interface{}) *mockReconciler_ensureBackupLeaseReleased_Call {
	return &mockReconciler_ensureBackupLeaseReleased_Call{Call: _e.mock.On("ensureBackupLeaseReleased", ctx, backup)}
}

func (_c *mockReconciler_ensureBackupLeaseReleased_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureBackupLeaseReleased_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureBackupLeaseReleased_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureBackupLeaseReleased_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureBackupLeaseReleased_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureBackupLeaseReleased_Call {
	_c.Call.Return(run)
	return _c
}

// ensureBackupRunCompleted provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureBackupRunCompleted(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureBackupRunCompleted")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureBackupRunCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureBackupRunCompleted'
type mockReconciler_ensureBackupRunCompleted_Call struct {
	*mock.Call
}

// ensureBackupRunCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureBackupRunCompleted(ctx interface{}, backup interface{}) *mockReconciler_ensureBackupRunCompleted_Call {
	return &mockReconciler_ensureBackupRunCompleted_Call{Call: _e.mock.On("ensureBackupRunCompleted", ctx, backup)}
}

func (_c *mockReconciler_ensureBackupRunCompleted_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureBackupRunCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureBackupRunCompleted_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureBackupRunCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureBackupRunCompleted_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureBackupRunCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// ensureBackupSetup provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureBackupSetup(ctx context.Context, backup *v1.Backup) (*v1.Backup, stageOutcome) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureBackupSetup")
	}

	var r0 *v1.Backup
	var r1 stageOutcome
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, backup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) stageOutcome); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Get(1).(stageOutcome)
	}

	return r0, r1
}

// mockReconciler_ensureBackupSetup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureBackupSetup'
type mockReconciler_ensureBackupSetup_Call struct {
	*mock.Call
}

// ensureBackupSetup is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureBackupSetup(ctx interface{}, backup interface{}) *mockReconciler_ensureBackupSetup_Call {
	return &mockReconciler_ensureBackupSetup_Call{Call: _e.mock.On("ensureBackupSetup", ctx, backup)}
}

func (_c *mockReconciler_ensureBackupSetup_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureBackupSetup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureBackupSetup_Call) Return(_a0 *v1.Backup, _a1 stageOutcome) *mockReconciler_ensureBackupSetup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureBackupSetup_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)) *mockReconciler_ensureBackupSetup_Call {
	_c.Call.Return(run)
	return _c
}

// ensureConditionsInitialized provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureConditionsInitialized(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureConditionsInitialized")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureConditionsInitialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureConditionsInitialized'
type mockReconciler_ensureConditionsInitialized_Call struct {
	*mock.Call
}

// ensureConditionsInitialized is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureConditionsInitialized(ctx interface{}, backup interface{}) *mockReconciler_ensureConditionsInitialized_Call {
	return &mockReconciler_ensureConditionsInitialized_Call{Call: _e.mock.On("ensureConditionsInitialized", ctx, backup)}
}

func (_c *mockReconciler_ensureConditionsInitialized_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureConditionsInitialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureConditionsInitialized_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureConditionsInitialized_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureConditionsInitialized_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureConditionsInitialized_Call {
	_c.Call.Return(run)
	return _c
}

// ensureMaintenanceActivated provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureMaintenanceActivated(ctx context.Context, backup *v1.Backup) (*v1.Backup, stageOutcome) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureMaintenanceActivated")
	}

	var r0 *v1.Backup
	var r1 stageOutcome
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, backup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) stageOutcome); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Get(1).(stageOutcome)
	}

	return r0, r1
}

// mockReconciler_ensureMaintenanceActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureMaintenanceActivated'
type mockReconciler_ensureMaintenanceActivated_Call struct {
	*mock.Call
}

// ensureMaintenanceActivated is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureMaintenanceActivated(ctx interface{}, backup interface{}) *mockReconciler_ensureMaintenanceActivated_Call {
	return &mockReconciler_ensureMaintenanceActivated_Call{Call: _e.mock.On("ensureMaintenanceActivated", ctx, backup)}
}

func (_c *mockReconciler_ensureMaintenanceActivated_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureMaintenanceActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureMaintenanceActivated_Call) Return(_a0 *v1.Backup, _a1 stageOutcome) *mockReconciler_ensureMaintenanceActivated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureMaintenanceActivated_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, stageOutcome)) *mockReconciler_ensureMaintenanceActivated_Call {
	_c.Call.Return(run)
	return _c
}

// ensureMaintenanceDeactivated provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureMaintenanceDeactivated(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureMaintenanceDeactivated")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureMaintenanceDeactivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureMaintenanceDeactivated'
type mockReconciler_ensureMaintenanceDeactivated_Call struct {
	*mock.Call
}

// ensureMaintenanceDeactivated is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureMaintenanceDeactivated(ctx interface{}, backup interface{}) *mockReconciler_ensureMaintenanceDeactivated_Call {
	return &mockReconciler_ensureMaintenanceDeactivated_Call{Call: _e.mock.On("ensureMaintenanceDeactivated", ctx, backup)}
}

func (_c *mockReconciler_ensureMaintenanceDeactivated_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureMaintenanceDeactivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureMaintenanceDeactivated_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureMaintenanceDeactivated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureMaintenanceDeactivated_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureMaintenanceDeactivated_Call {
	_c.Call.Return(run)
	return _c
}

// ensureOrphanedBackupDeleted provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureOrphanedBackupDeleted(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureOrphanedBackupDeleted")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureOrphanedBackupDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureOrphanedBackupDeleted'
type mockReconciler_ensureOrphanedBackupDeleted_Call struct {
	*mock.Call
}

// ensureOrphanedBackupDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureOrphanedBackupDeleted(ctx interface{}, backup interface{}) *mockReconciler_ensureOrphanedBackupDeleted_Call {
	return &mockReconciler_ensureOrphanedBackupDeleted_Call{Call: _e.mock.On("ensureOrphanedBackupDeleted", ctx, backup)}
}

func (_c *mockReconciler_ensureOrphanedBackupDeleted_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureOrphanedBackupDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureOrphanedBackupDeleted_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureOrphanedBackupDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureOrphanedBackupDeleted_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureOrphanedBackupDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// ensureProviderBackupCompleted provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureProviderBackupCompleted(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureProviderBackupCompleted")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureProviderBackupCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureProviderBackupCompleted'
type mockReconciler_ensureProviderBackupCompleted_Call struct {
	*mock.Call
}

// ensureProviderBackupCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureProviderBackupCompleted(ctx interface{}, backup interface{}) *mockReconciler_ensureProviderBackupCompleted_Call {
	return &mockReconciler_ensureProviderBackupCompleted_Call{Call: _e.mock.On("ensureProviderBackupCompleted", ctx, backup)}
}

func (_c *mockReconciler_ensureProviderBackupCompleted_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureProviderBackupCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureProviderBackupCompleted_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureProviderBackupCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureProviderBackupCompleted_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureProviderBackupCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// ensureProviderBackupCreated provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureProviderBackupCreated(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureProviderBackupCreated")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureProviderBackupCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureProviderBackupCreated'
type mockReconciler_ensureProviderBackupCreated_Call struct {
	*mock.Call
}

// ensureProviderBackupCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureProviderBackupCreated(ctx interface{}, backup interface{}) *mockReconciler_ensureProviderBackupCreated_Call {
	return &mockReconciler_ensureProviderBackupCreated_Call{Call: _e.mock.On("ensureProviderBackupCreated", ctx, backup)}
}

func (_c *mockReconciler_ensureProviderBackupCreated_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureProviderBackupCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureProviderBackupCreated_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureProviderBackupCreated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureProviderBackupCreated_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureProviderBackupCreated_Call {
	_c.Call.Return(run)
	return _c
}

// ensureProviderBackupDeleted provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureProviderBackupDeleted(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureProviderBackupDeleted")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureProviderBackupDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureProviderBackupDeleted'
type mockReconciler_ensureProviderBackupDeleted_Call struct {
	*mock.Call
}

// ensureProviderBackupDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureProviderBackupDeleted(ctx interface{}, backup interface{}) *mockReconciler_ensureProviderBackupDeleted_Call {
	return &mockReconciler_ensureProviderBackupDeleted_Call{Call: _e.mock.On("ensureProviderBackupDeleted", ctx, backup)}
}

func (_c *mockReconciler_ensureProviderBackupDeleted_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureProviderBackupDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureProviderBackupDeleted_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureProviderBackupDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureProviderBackupDeleted_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureProviderBackupDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// ensureVeleroStatusSynced provides a mock function with given fields: ctx, backup
func (_m *mockReconciler) ensureVeleroStatusSynced(ctx context.Context, backup *v1.Backup) (action, error) {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for ensureVeleroStatusSynced")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (action, error)); ok {
		return rf(ctx, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) action); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_ensureVeleroStatusSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureVeleroStatusSynced'
type mockReconciler_ensureVeleroStatusSynced_Call struct {
	*mock.Call
}

// ensureVeleroStatusSynced is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
func (_e *mockReconciler_Expecter) ensureVeleroStatusSynced(ctx interface{}, backup interface{}) *mockReconciler_ensureVeleroStatusSynced_Call {
	return &mockReconciler_ensureVeleroStatusSynced_Call{Call: _e.mock.On("ensureVeleroStatusSynced", ctx, backup)}
}

func (_c *mockReconciler_ensureVeleroStatusSynced_Call) Run(run func(ctx context.Context, backup *v1.Backup)) *mockReconciler_ensureVeleroStatusSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockReconciler_ensureVeleroStatusSynced_Call) Return(_a0 action, _a1 error) *mockReconciler_ensureVeleroStatusSynced_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_ensureVeleroStatusSynced_Call) RunAndReturn(run func(context.Context, *v1.Backup) (action, error)) *mockReconciler_ensureVeleroStatusSynced_Call {
	_c.Call.Return(run)
	return _c
}

// newMockReconciler creates a new instance of mockReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockReconciler {
	mock := &mockReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
