// Code generated by mockery v2.53.5. DO NOT EDIT.

package backup

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
	logr "github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
)

// mockReconciler is an autogenerated mock type for the reconciler type
type mockReconciler struct {
	mock.Mock
}

type mockReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockReconciler) EXPECT() *mockReconciler_Expecter {
	return &mockReconciler_Expecter{mock: &_m.Mock}
}

// checkBackupCancellation provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) checkBackupCancellation(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for checkBackupCancellation")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_checkBackupCancellation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkBackupCancellation'
type mockReconciler_checkBackupCancellation_Call struct {
	*mock.Call
}

// checkBackupCancellation is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) checkBackupCancellation(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_checkBackupCancellation_Call {
	return &mockReconciler_checkBackupCancellation_Call{Call: _e.mock.On("checkBackupCancellation", ctx, backup, logger)}
}

func (_c *mockReconciler_checkBackupCancellation_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_checkBackupCancellation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_checkBackupCancellation_Call) Return(_a0 action, _a1 error) *mockReconciler_checkBackupCancellation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_checkBackupCancellation_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_checkBackupCancellation_Call {
	_c.Call.Return(run)
	return _c
}

// checkBackupCompletion provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) checkBackupCompletion(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for checkBackupCompletion")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_checkBackupCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkBackupCompletion'
type mockReconciler_checkBackupCompletion_Call struct {
	*mock.Call
}

// checkBackupCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) checkBackupCompletion(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_checkBackupCompletion_Call {
	return &mockReconciler_checkBackupCompletion_Call{Call: _e.mock.On("checkBackupCompletion", ctx, backup, logger)}
}

func (_c *mockReconciler_checkBackupCompletion_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_checkBackupCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_checkBackupCompletion_Call) Return(_a0 action, _a1 error) *mockReconciler_checkBackupCompletion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_checkBackupCompletion_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_checkBackupCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// checkBackupDeletion provides a mock function with given fields: ctx, backup, logger
func (_m *mockReconciler) checkBackupDeletion(ctx context.Context, backup *v1.Backup, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, logger)

	if len(ret) == 0 {
		panic("no return value specified for checkBackupDeletion")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, logr.Logger) action); ok {
		r0 = rf(ctx, backup, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, logr.Logger) error); ok {
		r1 = rf(ctx, backup, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_checkBackupDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkBackupDeletion'
type mockReconciler_checkBackupDeletion_Call struct {
	*mock.Call
}

// checkBackupDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) checkBackupDeletion(ctx interface{}, backup interface{}, logger interface{}) *mockReconciler_checkBackupDeletion_Call {
	return &mockReconciler_checkBackupDeletion_Call{Call: _e.mock.On("checkBackupDeletion", ctx, backup, logger)}
}

func (_c *mockReconciler_checkBackupDeletion_Call) Run(run func(ctx context.Context, backup *v1.Backup, logger logr.Logger)) *mockReconciler_checkBackupDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_checkBackupDeletion_Call) Return(_a0 action, _a1 error) *mockReconciler_checkBackupDeletion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_checkBackupDeletion_Call) RunAndReturn(run func(context.Context, *v1.Backup, logr.Logger) (action, error)) *mockReconciler_checkBackupDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// checkMaintenanceModeActiveBeforeBackup provides a mock function with given fields: ctx, backup, namespace, logger
func (_m *mockReconciler) checkMaintenanceModeActiveBeforeBackup(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, namespace, logger)

	if len(ret) == 0 {
		panic("no return value specified for checkMaintenanceModeActiveBeforeBackup")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, namespace, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) action); ok {
		r0 = rf(ctx, backup, namespace, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, string, logr.Logger) error); ok {
		r1 = rf(ctx, backup, namespace, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkMaintenanceModeActiveBeforeBackup'
type mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call struct {
	*mock.Call
}

// checkMaintenanceModeActiveBeforeBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - namespace string
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) checkMaintenanceModeActiveBeforeBackup(ctx interface{}, backup interface{}, namespace interface{}, logger interface{}) *mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call {
	return &mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call{Call: _e.mock.On("checkMaintenanceModeActiveBeforeBackup", ctx, backup, namespace, logger)}
}

func (_c *mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call) Run(run func(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger)) *mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(string), args[3].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call) Return(_a0 action, _a1 error) *mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call) RunAndReturn(run func(context.Context, *v1.Backup, string, logr.Logger) (action, error)) *mockReconciler_checkMaintenanceModeActiveBeforeBackup_Call {
	_c.Call.Return(run)
	return _c
}

// checkMaintenanceModeNotActiveAfterBackup provides a mock function with given fields: ctx, backup, namespace, logger
func (_m *mockReconciler) checkMaintenanceModeNotActiveAfterBackup(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, namespace, logger)

	if len(ret) == 0 {
		panic("no return value specified for checkMaintenanceModeNotActiveAfterBackup")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, namespace, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) action); ok {
		r0 = rf(ctx, backup, namespace, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, string, logr.Logger) error); ok {
		r1 = rf(ctx, backup, namespace, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkMaintenanceModeNotActiveAfterBackup'
type mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call struct {
	*mock.Call
}

// checkMaintenanceModeNotActiveAfterBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - namespace string
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) checkMaintenanceModeNotActiveAfterBackup(ctx interface{}, backup interface{}, namespace interface{}, logger interface{}) *mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call {
	return &mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call{Call: _e.mock.On("checkMaintenanceModeNotActiveAfterBackup", ctx, backup, namespace, logger)}
}

func (_c *mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call) Run(run func(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger)) *mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(string), args[3].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call) Return(_a0 action, _a1 error) *mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call) RunAndReturn(run func(context.Context, *v1.Backup, string, logr.Logger) (action, error)) *mockReconciler_checkMaintenanceModeNotActiveAfterBackup_Call {
	_c.Call.Return(run)
	return _c
}

// checkVeleroBackupCompletion provides a mock function with given fields: ctx, backup, namespace, logger
func (_m *mockReconciler) checkVeleroBackupCompletion(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, namespace, logger)

	if len(ret) == 0 {
		panic("no return value specified for checkVeleroBackupCompletion")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, namespace, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) action); ok {
		r0 = rf(ctx, backup, namespace, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, string, logr.Logger) error); ok {
		r1 = rf(ctx, backup, namespace, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_checkVeleroBackupCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkVeleroBackupCompletion'
type mockReconciler_checkVeleroBackupCompletion_Call struct {
	*mock.Call
}

// checkVeleroBackupCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - namespace string
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) checkVeleroBackupCompletion(ctx interface{}, backup interface{}, namespace interface{}, logger interface{}) *mockReconciler_checkVeleroBackupCompletion_Call {
	return &mockReconciler_checkVeleroBackupCompletion_Call{Call: _e.mock.On("checkVeleroBackupCompletion", ctx, backup, namespace, logger)}
}

func (_c *mockReconciler_checkVeleroBackupCompletion_Call) Run(run func(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger)) *mockReconciler_checkVeleroBackupCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(string), args[3].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_checkVeleroBackupCompletion_Call) Return(_a0 action, _a1 error) *mockReconciler_checkVeleroBackupCompletion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_checkVeleroBackupCompletion_Call) RunAndReturn(run func(context.Context, *v1.Backup, string, logr.Logger) (action, error)) *mockReconciler_checkVeleroBackupCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// checkVeleroBackupResource provides a mock function with given fields: ctx, backup, namespace, logger
func (_m *mockReconciler) checkVeleroBackupResource(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, namespace, logger)

	if len(ret) == 0 {
		panic("no return value specified for checkVeleroBackupResource")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, namespace, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) action); ok {
		r0 = rf(ctx, backup, namespace, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, string, logr.Logger) error); ok {
		r1 = rf(ctx, backup, namespace, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_checkVeleroBackupResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkVeleroBackupResource'
type mockReconciler_checkVeleroBackupResource_Call struct {
	*mock.Call
}

// checkVeleroBackupResource is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - namespace string
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) checkVeleroBackupResource(ctx interface{}, backup interface{}, namespace interface{}, logger interface{}) *mockReconciler_checkVeleroBackupResource_Call {
	return &mockReconciler_checkVeleroBackupResource_Call{Call: _e.mock.On("checkVeleroBackupResource", ctx, backup, namespace, logger)}
}

func (_c *mockReconciler_checkVeleroBackupResource_Call) Run(run func(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger)) *mockReconciler_checkVeleroBackupResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(string), args[3].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_checkVeleroBackupResource_Call) Return(_a0 action, _a1 error) *mockReconciler_checkVeleroBackupResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_checkVeleroBackupResource_Call) RunAndReturn(run func(context.Context, *v1.Backup, string, logr.Logger) (action, error)) *mockReconciler_checkVeleroBackupResource_Call {
	_c.Call.Return(run)
	return _c
}

// checkVeleroBackupStorage provides a mock function with given fields: ctx, backup, namespace, logger
func (_m *mockReconciler) checkVeleroBackupStorage(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger) (action, error) {
	ret := _m.Called(ctx, backup, namespace, logger)

	if len(ret) == 0 {
		panic("no return value specified for checkVeleroBackupStorage")
	}

	var r0 action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) (action, error)); ok {
		return rf(ctx, backup, namespace, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string, logr.Logger) action); ok {
		r0 = rf(ctx, backup, namespace, logger)
	} else {
		r0 = ret.Get(0).(action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, string, logr.Logger) error); ok {
		r1 = rf(ctx, backup, namespace, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReconciler_checkVeleroBackupStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkVeleroBackupStorage'
type mockReconciler_checkVeleroBackupStorage_Call struct {
	*mock.Call
}

// checkVeleroBackupStorage is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *v1.Backup
//   - namespace string
//   - logger logr.Logger
func (_e *mockReconciler_Expecter) checkVeleroBackupStorage(ctx interface{}, backup interface{}, namespace interface{}, logger interface{}) *mockReconciler_checkVeleroBackupStorage_Call {
	return &mockReconciler_checkVeleroBackupStorage_Call{Call: _e.mock.On("checkVeleroBackupStorage", ctx, backup, namespace, logger)}
}

func (_c *mockReconciler_checkVeleroBackupStorage_Call) Run(run func(ctx context.Context, backup *v1.Backup, namespace string, logger logr.Logger)) *mockReconciler_checkVeleroBackupStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(string), args[3].(logr.Logger))
	})
	return _c
}

func (_c *mockReconciler_checkVeleroBackupStorage_Call) Return(_a0 action, _a1 error) *mockReconciler_checkVeleroBackupStorage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockReconciler_checkVeleroBackupStorage_Call) RunAndReturn(run func(context.Context, *v1.Backup, string, logr.Logger) (action, error)) *mockReconciler_checkVeleroBackupStorage_Call {
	_c.Call.Return(run)
	return _c
}

// newMockReconciler creates a new instance of mockReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockReconciler {
	mock := &mockReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
