// Code generated by mockery v2.53.5. DO NOT EDIT.

package leases

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, namespace, name
func (_m *MockResolver) Get(ctx context.Context, namespace string, name string) (client.Object, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 client.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (client.Object, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) client.Object); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResolver_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockResolver_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockResolver_Expecter) Get(ctx interface{}, namespace interface{}, name interface{}) *MockResolver_Get_Call {
	return &MockResolver_Get_Call{Call: _e.mock.On("Get", ctx, namespace, name)}
}

func (_c *MockResolver_Get_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockResolver_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockResolver_Get_Call) Return(_a0 client.Object, _a1 error) *MockResolver_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResolver_Get_Call) RunAndReturn(run func(context.Context, string, string) (client.Object, error)) *MockResolver_Get_Call {
	_c.Call.Return(run)
	return _c
}

// IsTerminal provides a mock function with given fields: holder
func (_m *MockResolver) IsTerminal(holder client.Object) bool {
	ret := _m.Called(holder)

	if len(ret) == 0 {
		panic("no return value specified for IsTerminal")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(client.Object) bool); ok {
		r0 = rf(holder)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockResolver_IsTerminal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTerminal'
type MockResolver_IsTerminal_Call struct {
	*mock.Call
}

// IsTerminal is a helper method to define mock.On call
//   - holder client.Object
func (_e *MockResolver_Expecter) IsTerminal(holder interface{}) *MockResolver_IsTerminal_Call {
	return &MockResolver_IsTerminal_Call{Call: _e.mock.On("IsTerminal", holder)}
}

func (_c *MockResolver_IsTerminal_Call) Run(run func(holder client.Object)) *MockResolver_IsTerminal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.Object))
	})
	return _c
}

func (_c *MockResolver_IsTerminal_Call) Return(_a0 bool) *MockResolver_IsTerminal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolver_IsTerminal_Call) RunAndReturn(run func(client.Object) bool) *MockResolver_IsTerminal_Call {
	_c.Call.Return(run)
	return _c
}

// Kind provides a mock function with no fields
func (_m *MockResolver) Kind() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockResolver_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type MockResolver_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *MockResolver_Expecter) Kind() *MockResolver_Kind_Call {
	return &MockResolver_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *MockResolver_Kind_Call) Run(run func()) *MockResolver_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolver_Kind_Call) Return(_a0 string) *MockResolver_Kind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolver_Kind_Call) RunAndReturn(run func() string) *MockResolver_Kind_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
