// Code generated by mockery v2.53.5. DO NOT EDIT.

package restore

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockScaleManager is an autogenerated mock type for the scaleManager type
type mockScaleManager struct {
	mock.Mock
}

type mockScaleManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockScaleManager) EXPECT() *mockScaleManager_Expecter {
	return &mockScaleManager_Expecter{mock: &_m.Mock}
}

// ScaleDown provides a mock function with given fields: ctx
func (_m *mockScaleManager) ScaleDown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ScaleDown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockScaleManager_ScaleDown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScaleDown'
type mockScaleManager_ScaleDown_Call struct {
	*mock.Call
}

// ScaleDown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockScaleManager_Expecter) ScaleDown(ctx interface{}) *mockScaleManager_ScaleDown_Call {
	return &mockScaleManager_ScaleDown_Call{Call: _e.mock.On("ScaleDown", ctx)}
}

func (_c *mockScaleManager_ScaleDown_Call) Run(run func(ctx context.Context)) *mockScaleManager_ScaleDown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockScaleManager_ScaleDown_Call) Return(_a0 error) *mockScaleManager_ScaleDown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockScaleManager_ScaleDown_Call) RunAndReturn(run func(context.Context) error) *mockScaleManager_ScaleDown_Call {
	_c.Call.Return(run)
	return _c
}

// ScaleUp provides a mock function with given fields: ctx
func (_m *mockScaleManager) ScaleUp(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ScaleUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockScaleManager_ScaleUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScaleUp'
type mockScaleManager_ScaleUp_Call struct {
	*mock.Call
}

// ScaleUp is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockScaleManager_Expecter) ScaleUp(ctx interface{}) *mockScaleManager_ScaleUp_Call {
	return &mockScaleManager_ScaleUp_Call{Call: _e.mock.On("ScaleUp", ctx)}
}

func (_c *mockScaleManager_ScaleUp_Call) Run(run func(ctx context.Context)) *mockScaleManager_ScaleUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockScaleManager_ScaleUp_Call) Return(_a0 error) *mockScaleManager_ScaleUp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockScaleManager_ScaleUp_Call) RunAndReturn(run func(context.Context) error) *mockScaleManager_ScaleUp_Call {
	_c.Call.Return(run)
	return _c
}

// newMockScaleManager creates a new instance of mockScaleManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockScaleManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockScaleManager {
	mock := &mockScaleManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
