// Code generated by mockery v2.53.5. DO NOT EDIT.

package maintenance

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: title, text
func (_m *MockService) Activate(title string, text string) {
	_m.Called(title, text)
}

// MockService_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockService_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - title string
//   - text string
func (_e *MockService_Expecter) Activate(title interface{}, text interface{}) *MockService_Activate_Call {
	return &MockService_Activate_Call{Call: _e.mock.On("Activate", title, text)}
}

func (_c *MockService_Activate_Call) Run(run func(title string, text string)) *MockService_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockService_Activate_Call) Return() *MockService_Activate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Activate_Call) RunAndReturn(run func(string, string)) *MockService_Activate_Call {
	_c.Run(run)
	return _c
}

// Deactivate provides a mock function with no fields
func (_m *MockService) Deactivate() {
	_m.Called()
}

// MockService_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockService_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
func (_e *MockService_Expecter) Deactivate() *MockService_Deactivate_Call {
	return &MockService_Deactivate_Call{Call: _e.mock.On("Deactivate")}
}

func (_c *MockService_Deactivate_Call) Run(run func()) *MockService_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Deactivate_Call) Return() *MockService_Deactivate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Deactivate_Call) RunAndReturn(run func()) *MockService_Deactivate_Call {
	_c.Run(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
