// Code generated by mockery v2.53.5. DO NOT EDIT.

package config

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGateway is an autogenerated mock type for the Gateway type
type MockGateway struct {
	mock.Mock
}

type MockGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateway) EXPECT() *MockGateway_Expecter {
	return &MockGateway_Expecter{mock: &_m.Mock}
}

// RetryLimit provides a mock function with given fields: _a0
func (_m *MockGateway) RetryLimit(_a0 context.Context) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RetryLimit")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGateway_RetryLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryLimit'
type MockGateway_RetryLimit_Call struct {
	*mock.Call
}

// RetryLimit is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockGateway_Expecter) RetryLimit(_a0 interface{}) *MockGateway_RetryLimit_Call {
	return &MockGateway_RetryLimit_Call{Call: _e.mock.On("RetryLimit", _a0)}
}

func (_c *MockGateway_RetryLimit_Call) Run(run func(_a0 context.Context)) *MockGateway_RetryLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGateway_RetryLimit_Call) Return(_a0 int, _a1 error) *MockGateway_RetryLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGateway_RetryLimit_Call) RunAndReturn(run func(context.Context) (int, error)) *MockGateway_RetryLimit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGateway creates a new instance of MockGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateway {
	mock := &MockGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
