apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-backup-operator-additional-images
  labels:
    {{- include "k8s-backup-operator.labels" . | nindent 4 }}
data:
  kubectlImage: "{{ .Values.additionalImages.kubectl }}"
