apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-backupschedule-editor-role
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - backupschedules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - backupschedules/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - backupschedules/status
    verbs:
      - get
      - patch
      - update
