apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-backup-editor-role
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-backup-editor-role-binding
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "k8s-backup-operator.name" . }}-backup-editor-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "k8s-backup-operator.name" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
  - kind: ServiceAccount
    name: '{{ include "k8s-backup-operator.name" . }}-scheduled-backup-creator-manager'
    namespace: '{{ .Release.Namespace }}'
  - kind: ServiceAccount
    name: '{{ include "k8s-backup-operator.name" . }}-garbage-collection-manager'
    namespace: '{{ .Release.Namespace }}'