apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-backup-viewer-role
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - backups/status
  verbs:
  - get