apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-cronjob-editor-role
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-cronjob-editor-role-binding
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "k8s-backup-operator.name" . }}-cronjob-editor-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "k8s-backup-operator.name" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'