apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-controller-manager
  labels:
    app.kubernetes.io/component: manager
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
    {{- include "k8s-backup-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "k8s-backup-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      initContainers:
        - name: default-schedule-cr
          image: "{{ .Values.initContainer.image.registry }}/{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          command:
            - sh
            - -c
            - |
              if ! kubectl get backupschedules.k8s.cloudogu.com {{ .Values.initContainer.schedule.name }} >/dev/null 2>&1; then
              cat <<EOF | kubectl apply -f -
              apiVersion: k8s.cloudogu.com/v1
              kind: BackupSchedule
              metadata:
                name: {{ .Values.initContainer.schedule.name }}
              spec:
                schedule: {{ .Values.initContainer.schedule.cron }}
                provider: "velero"
              EOF
              else
                echo "CR '{{ .Values.initContainer.schedule.name }}' already exists, skipping creation"
              fi
      containers:
      - args:
        - operator
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        env:
        - name: LOG_LEVEL
          value: {{ .Values.manager.env.logLevel | default "info" }}
        - name: STAGE
          value: {{ .Values.manager.env.stage | default "production" }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BACKUP_RETRY_TIME_LIMIT
          value: {{ .Values.backup.retryTimeLimit | default 60 | quote }}
        image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}"
        imagePullPolicy: {{ .Values.manager.imagePullPolicy | default "IfNotPresent" }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.manager.resources | nindent 10
          }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "k8s-backup-operator.name" . }}-controller-manager
      terminationGracePeriodSeconds: 10