apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-garbage-collection-manager
  labels:
    app.kubernetes.io/component: garbage-collector
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
spec:
  jobTemplate:
    metadata:
      labels:
        {{- include "k8s-backup-operator.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{- include "k8s-backup-operator.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
            {{- end }}
          containers:
          - args:
            - gc
            - --strategy={{ .Values.retention.strategy }}
            env:
            - name: STAGE
              value: {{ .Values.manager.env.stage }}
            - name: LOG_LEVEL
              value: {{ .Values.manager.env.logLevel }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            image: "{{ .Values.manager.image.registry }}/{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}"
            imagePullPolicy: {{ .Values.manager.imagePullPolicy }}
            name: garbage-collector
            resources:
            {{- toYaml .Values.kubeRbacProxy.resources | nindent 14 }}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - mountPath: /config/retention
              name: retention-config
              readOnly: true
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: k8s-backup-operator-garbage-collection-manager
          volumes:
          - configMap:
              name: k8s-backup-operator-retention
              optional: true
            name: retention-config
  schedule: '{{ .Values.retention.garbageCollectionCron }}'