apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-create-backup-script
  labels:
    app: ces
    k8s.cloudogu.com/part-of: backup
    app.kubernetes.io/name: scheduled-backup-creator
    app.kubernetes.io/part-of: k8s-backup-operator
data:
  entrypoint.sh: |
    #!/bin/bash
    TIMESTAMP=$(date +"%y%m%d%H%M%S")
    CR_DEFINITION_TEXT="
    apiVersion: k8s.cloudogu.com/v1
    kind: Backup
    metadata:
      labels:
        app: ces
        k8s.cloudogu.com/part-of: backup
        app.kubernetes.io/name: backup
        app.kubernetes.io/part-of: k8s-backup-operator
        app.kubernetes.io/created-by: k8s-backup-operator
      name: ${SCHEDULED_BACKUP_NAME}-${TIMESTAMP}
      namespace: ${NAMESPACE}
    spec:
      provider: ${PROVIDER}
    "
    echo "${CR_DEFINITION_TEXT}" | kubectl apply -f -
