apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-backup-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: '{{ include "k8s-backup-operator.name" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
