apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-metrics-reader
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get