apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-metrics-reader-role
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get