---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backup-operator-deny-ingress
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "k8s-backup-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    - matchLabels:
        app: backup-operator
  policyTypes:
    - Ingress
