# This is needed to read CRDs for k8s.cloudogu.com as well as all resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-ownerreference-role
  labels:
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch