# This is needed to read CRDs for k8s.cloudogu.com as well as all resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-ownerreference-role-binding
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "k8s-backup-operator.name" . }}-ownerreference-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "k8s-backup-operator.name" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'