apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-backup-operator-restore-dogu-modifier
  labels:
    {{- include "k8s-backup-operator.labels" . | nindent 4 }}
data:
  dogu-modifier: |
    resourceModifierRules:
      - conditions:
          groupResource: dogus.k8s.cloudogu.com
          namespaces:
            - {{ .Release.Namespace }}
        patches:
          - operation: add
            path: "/metadata/annotations/k8s.cloudogu.com~1was-restored"
            value: "true"
