apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-garbage-collection-manager
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-scheduled-backup-creator-manager
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}