# This is necessary to scale workloads down before and up after a restore,
# and to check the provider deployment's readiness. Deployments have no watch
# because a live check is more important to check the provider readiness.
# The others get watch to enable the cache for them.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-backup-operator.name" . }}-workload-scale-role
  labels:
    app.kubernetes.io/component: rbac
  {{- include "k8s-backup-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - replicasets
    verbs:
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - list
      - watch
      - update
