// Code generated by mockery v2.53.3. DO NOT EDIT.

package ecosystem

import mock "github.com/stretchr/testify/mock"

// MockBackupsGetter is an autogenerated mock type for the BackupsGetter type
type MockBackupsGetter struct {
	mock.Mock
}

type MockBackupsGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackupsGetter) EXPECT() *MockBackupsGetter_Expecter {
	return &MockBackupsGetter_Expecter{mock: &_m.Mock}
}

// Backups provides a mock function with given fields: namespace
func (_m *MockBackupsGetter) Backups(namespace string) BackupInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Backups")
	}

	var r0 BackupInterface
	if rf, ok := ret.Get(0).(func(string) BackupInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(BackupInterface)
		}
	}

	return r0
}

// MockBackupsGetter_Backups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backups'
type MockBackupsGetter_Backups_Call struct {
	*mock.Call
}

// Backups is a helper method to define mock.On call
//   - namespace string
func (_e *MockBackupsGetter_Expecter) Backups(namespace interface{}) *MockBackupsGetter_Backups_Call {
	return &MockBackupsGetter_Backups_Call{Call: _e.mock.On("Backups", namespace)}
}

func (_c *MockBackupsGetter_Backups_Call) Run(run func(namespace string)) *MockBackupsGetter_Backups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBackupsGetter_Backups_Call) Return(_a0 BackupInterface) *MockBackupsGetter_Backups_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackupsGetter_Backups_Call) RunAndReturn(run func(string) BackupInterface) *MockBackupsGetter_Backups_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBackupsGetter creates a new instance of MockBackupsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackupsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackupsGetter {
	mock := &MockBackupsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
